### ISSUE TITLE
includes is not a function

### ISSUE THREAD

**Issue by mlissner** [mozilla/web-ext#1032]
### Is this a feature request or a bug?

Bug

### What is the current behavior?

When I run the lint command, it crashes with the following stacktrace:

```
↪ web-ext lint
_const.MESSAGE_TYPES.includes is not a function

lint: TypeError: _const.MESSAGE_TYPES.includes is not a function
    at Message.set (/usr/local/lib/node_modules/web-ext/node_modules/addons-linter/dist/webpack:/src/message.js:52:24)
    at new Message (/usr/local/lib/node_modules/web-ext/node_modules/addons-linter/dist/webpack:/src/message.js:26:5)
    at Collector._addMessage (/usr/local/lib/node_modules/web-ext/node_modules/addons-linter/dist/webpack:/src/collector.js:39:19)
    at Collector.addNotice (/usr/local/lib/node_modules/web-ext/node_modules/addons-linter/dist/webpack:/src/collector.js:102:10)
    at /usr/local/lib/node_modules/web-ext/node_modules/addons-linter/dist/webpack:/src/linter.js:611:32
    at lib$es6$promise$$internal$$tryCatch (/usr/local/lib/node_modules/web-ext/node_modules/node-firefox-connect/node_modules/es6-promise/dist/es6-promise.js:331:16)
    at lib$es6$promise$$internal$$invokeCallback (/usr/local/lib/node_modules/web-ext/node_modules/node-firefox-connect/node_modules/es6-promise/dist/es6-promise.js:343:17)
    at lib$es6$promise$$internal$$publish (/usr/local/lib/node_modules/web-ext/node_modules/node-firefox-connect/node_modules/es6-promise/dist/es6-promise.js:314:11)
    at lib$es6$promise$asap$$flush (/usr/local/lib/node_modules/web-ext/node_modules/node-firefox-connect/node_modules/es6-promise/dist/es6-promise.js:125:9)
    at nextTickCallbackWith0Args (node.js:436:9)
```

### What is the expected or desired behavior?

It works without crashing. (Or, if this is something to do with my code, it makes that clear somehow.)

### Version information (for bug reports)

```
↪ web-ext --version
2.0.0
```

* **Firefox version**: 57.0a1 (2017-08-05) (64-bit)
* **Your OS and version**: Ubuntu 17.04
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
```
↪ node --version && npm --version && web-ext --version
v4.7.2
3.5.2
2.0.0
```

**Comment by wagnerand** [comment]
I am fairly confident that this is because you're using an old version of NodeJS. `web-ext` 2.0 requires at least NodeJS 6.

**Comment by wagnerand** [comment]
Feel free to reopen if I am wrong :)

**Comment by mlissner** [comment]
I don't have reopen rights for this project, but, um, shouldn't web-ext block the installation if node is too old for it? Also, is it crazy to update our install instructions to say this?

**Comment by wagnerand** [comment]
You can always reopen your own issues.

> shouldn't web-ext block the installation if node is too old for it?

A question for @kumar303 :)

> Also, is it crazy to update our install instructions to say this?

The README.md includes a section about the requirements. Where would you expect to read this?

**Comment by mlissner** [comment]
> You can always reopen your own issues.

I would have thought so too, but...I didn't have the re-open button. Weird.

> Where would you expect to read this?

I guess I missed it in the readme. I was getting info from the Mozilla blog, where there's an article about web-ext. Probably not the canonical source!

**Comment by kumar303** [comment]
Hi. Sorry about the confusion. The `package.json` already specifies [Node 6 as a requirement](https://github.com/mozilla/web-ext/blob/master/package.json#L7) but I believe in older versions of Node (like yours) this is only shown as a warning during installation for some reason. If you have a link to the blog you found web-ext from, I can look at getting an edit to it.

**Comment by mlissner** [comment]
*Figures!*

Here's the link: https://blog.mozilla.org/addons/2016/07/27/linting-and-automatically-reloading-webextensions/

**Comment by kumar303** [comment]
ok, thanks. That links to the MDN docs which were missing a note about how Node 6 is required. I just updated them: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext

Thanks for taking the time to report an issue.
