### ISSUE TITLE
web-ext no longer works with Firefox Nightly

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/web-ext#1068]
### Is this a feature request or a bug?

bug

### What is the current behavior?

Running web-ext run --firefox=\"/Applications/Firefox Nightly.app\" no longer works with current Nightly builds of Firefox. Firefox Nightly starts and immediately quits. The following message appears in the terminal:

```
run: WebExtError: Temporary add-on installation is not supported in this version of Firefox (you need Firefox 49 or higher). For older Firefox versions, use --pre-install
    at FirefoxDesktopExtensionRunner._callee6$ (/Users/cadeyrn/localhost/fx-addons/addons/newtaboverride/node_modules/web-ext/dist/webpack:/src/extension-runners/firefox-desktop.js:9:30252)
    at tryCatch (/Users/cadeyrn/localhost/fx-addons/addons/newtaboverride/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/cadeyrn/localhost/fx-addons/addons/newtaboverride/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as throw] (/Users/cadeyrn/localhost/fx-addons/addons/newtaboverride/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/cadeyrn/localhost/fx-addons/addons/newtaboverride/node_modules/web-ext/dist/webpack:/~/babel-runtime/helpers/asyncToGenerator.js:17:1)
    at /Users/cadeyrn/localhost/fx-addons/addons/newtaboverride/node_modules/web-ext/dist/webpack:/~/babel-runtime/helpers/asyncToGenerator.js:30:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! newtaboberride@8.0.0 run:nightly: `cd src && web-ext run --firefox="/Applications/Firefox Nightly.app"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the newtaboberride@8.0.0 run:nightly script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

It still works with Firefox Beta and Firefox Stable.

### What is the expected or desired behavior?

It works.

### Version information (for bug reports)

* **Firefox version**: Firefox Nightly 57
* **Your OS and version**: macOS High Sierra Developer Beta
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
v8.1.3
5.3.0

**Comment by cadeyrn** [comment]
Seems it was was a Firefox bug and got fixed, it works in today's Nightly.

**Comment by kumar303** [comment]
Thanks for taking the time to report it.

**Comment by kumar303** [comment]
Just for future reference, a `--verbose` log is really helpful in bug reports. In this case it would have shown why web-ext thought the remote debugger did not support temporary installation.
