### ISSUE TITLE
Crash after 3 seconds with "Unexpected packet from actor root ..."

### ISSUE THREAD

**Issue by jehon** [mozilla/web-ext#1069]
### Is this a feature request or a bug?
Bug

### What is the current behavior?
When launching:
npm run web-ext 

The script display correctly:
```
Running web extension from xxx
You are using 32-bit version of Firefox on 64-bit versions of the Windows.
Some features may not work correctly in this version. You should upgrade Firefox to the latest 64-bit version now!
Use --verbose or open Tools > Web Developer > Browser Console to see logging
Installed xxx as a temporary add-on
The extension will reload if any source file changes
Press R to reload (and Ctrl-C to quit)
```

The browser open correctly, with the browser console fine.

After 3 seconds, I receive this message, and everything crash:

```
C:\xxx\node_modules\firefox-client\lib\client.js:173
      throw new Error("Unexpected packet from actor " +  message.from
            ^
Error: Unexpected packet from actor root{"from":"root","addons":[{"actor":"server2.conn0.addon6","id":"aushelper@mozilla.org","name":"Application Update Service Helper","iconURL":null,"debuggable":true,"temporarilyInstalled":false,"consoleActor":"server2.conn0.addonConsole20","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server2.conn0.addon7","id":"clicktoplay-rollout@mozilla.org","name":"Click-to-Play staged rollout","iconURL":null,"debuggable":true,"temporarilyInstalled":false,"consoleActor":"server2.conn0.addonConsole21","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server2.conn0.addon8","id":"e10srollout@mozilla.org","name":"Multi-process staged rollout","iconURL":null,"debuggable":true,"temporarilyInstalled":false,"consoleActor":"server2.conn0.addonConsole22","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server2.conn0.addon9","id":"firefox@getpocket.com","name":"Pocket","iconURL":null,"debuggable":true,"temporarilyInstalled":false,"consoleActor":"server2.conn0.addonConsole23","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server2.conn0.addon10","id":"followonsearch@mozilla.com","name":"Follow-on Search Telemetry","iconURL":null,"debuggable":true,"temporarilyInstalled":false,"consoleActor":"server2.conn0.addonConsole24","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server2.conn0.addon11","id":"screenshots@mozilla.org","name":"Firefox Screenshots","iconURL":null,"debuggable":true,"temporarilyInstalled":false,"consoleActor":"server2.conn0.addonConsole25","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server2.conn0.addon12","id":"shield-recipe-client@mozilla.org","name":"Shield Recipe Client","iconURL":null,"debuggable":true,"temporarilyInstalled":false,"consoleActor":"server2.conn0.addonConsole26","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server2.conn0.addon13","id":"webcompat@mozilla.org","name":"Web Compat","iconURL":null,"debuggable":true,"temporarilyInstalled":false,"consoleActor":"server2.conn0.addonConsole27","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server2.conn0.addon14","id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","name":"Thème par défaut","iconURL":"chrome://browser/content/default-theme-icon.svg","temporarilyInstalled":false,"consoleActor":"server2.conn0.addonConsole28","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server2.conn0.webExtensionAddon15","id":"galien@groupe-epc.be","name":"EPC_Extensions","url":"file:///C:/Users/zzz/src/firefox-extension/","iconURL":"file:///C:/Users/zzz/src/firefox-extension/icons/epc.png","debuggable":true,"temporarilyInstalled":true,"isWebExtension":true,"manifestURL":null},{"actor":"server2.conn0.addon16","id":"firefox-compact-light@mozilla.org@personas.mozilla.org","name":"Compact clair","iconURL":"resource:///chrome/browser/content/browser/defaultthemes/compactlight.icon.svg","consoleActor":"server2.conn0.addonConsole29","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server2.conn0.addon17","id":"firefox-compact-dark@mozilla.org@personas.mozilla.org","name":"Compact sombre","iconURL":"resource:///chrome/browser/content/browser/defaultthemes/compactdark.icon.svg","consoleActor":"server2.conn0.addonConsole30","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server2.conn0.addon33","id":"gmp-gmpopenh264","name":"Codec vidéo OpenH264 fourni par Cisco Systems, Inc.","consoleActor":"server2.conn0.addonConsole34","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server2.conn0.addon35","id":"gmp-widevinecdm","name":"Module de déchiffrement de contenu Widevine fourni par Google Inc.","consoleActor":"server2.conn0.addonConsole36","traits":{"highlightable":false,"networkMonitor":false}}]}
    at EventEmitter.handleMessage (C:\xxx\node_modules\firefox-client\lib\client.js:173:13)
    at EventEmitter.readMessage (C:\xxx\node_modules\firefox-client\lib\client.js:220:10)
    at EventEmitter.onData (C:\xxx\node_modules\firefox-client\lib\client.js:186:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
[firefox-profile] cannot delete profileDir on exit C:\yyy\AppData\Local\Temp\3777d24e-8e8f-42bc-8d40-efc1407e88cf { Error: EBUSY: resource busy or locked, unlink 'C:\yyy\AppData\Local\Temp\3777d24e-8e8f-42bc-8d40-efc1407e88cf\cert8.db'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1103:18)
    at rimrafSync (C:\xxx\node_modules\fs-extra\lib\remove\rimraf.js:254:15)
    at options.readdirSync.forEach.f (C:\xxx\node_modules\fs-extra\lib\remove\rimraf.js:291:39)
    at Array.forEach (native)
    at rmkidsSync (C:\xxx\node_modules\fs-extra\lib\remove\rimraf.js:291:26)
    at rmdirSync (C:\xxx\node_modules\fs-extra\lib\remove\rimraf.js:283:7)
    at Function.rimrafSync [as sync] (C:\xxx\node_modules\fs-extra\lib\remove\rimraf.js:252:7)
    at Object.removeSync (C:\xxx\node_modules\fs-extra\lib\remove\index.js:6:17)
    at FirefoxProfile._cleanOnExit (C:\xxx\node_modules\firefox-profile\lib\firefox_profile.js:253:10)
  errno: -4082,
  code: 'EBUSY',
  syscall: 'unlink',
  path: 'C:\\yyy\\AppData\\Local\\Temp\\3777d24e-8e8f-42bc-8d40-efc1407e88cf\\cert8.db' }

```
### What is the expected or desired behavior?

I would expect Firefox to remain open and not to crash :-)

### Version information (for bug reports)

* **Firefox version**: 55.0.3 (32 bits)
* **Your OS and version**: Windows 10 Pro, 64bits
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version

node --version:    v6.11.0
npm --version:     3.10.10
web-ext --version: 2.0.0
````

Two particularities:
- web-ext is not installed globally, but instead used as an alias in package.json
npm run web-ext => "web-ext run --browser-console"

- My firefox is 32bits on a 64bits system. This is for context reasons.

Thanks for your support !

**Comment by jehon** [comment]
I have the same problem when loading my traditionnal profile with
--firefox-profile=C:\...

while that profile is working correctly when launching firefox without web-ext (it's my usual browser).

**Comment by jehon** [comment]
It seems that it was coming from too frequent refresh.

I had a script logging information into the firefox-extension folder, forcing application to reload every seconds. That caused the bug.

Removing the log solved the problem.

I am closing now.

Thanks everybody !

**Comment by kumar303** [comment]
Hmm, that's odd that it caused a crash but you could also use [`--ignore-files`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#--ignore-files_-i) to stop the log file from triggering auto-reloads.

**Comment by jehon** [comment]
Thanks for the tip!

**Comment by sneakypete81** [comment]
@kumar303: Could we reopen this, please? As you mentioned, auto-reloads shouldn't cause crashes.

I have a build environment where webpack is running in watch mode, and "web-ext run" is using the result. On some machines I get this crash unless I add a fixed delay to prevent webpack from updating the extension while web-ext is starting. After web-ext and firefox are running, everything works fine - I can modify the source, webpack updates the extension, and web-ext reloads the it in the browser.

I have a good consistent repro on one machine, and I'm happy to help with testing.

**Comment by kumar303** [comment]
Yeah, this should not have been closed. However, https://github.com/mozilla/web-ext/issues/1092 has a verbose log which will be really helpful in fixing it so I'll consider this a dupe of https://github.com/mozilla/web-ext/issues/1092
