### ISSUE TITLE
web-ext run: Error: getaddrinfo ENOENT localhost:6005

### ISSUE THREAD

**Issue by ritwickdey** [mozilla/web-ext#1083]
### Is this a feature request or a bug?
Bug

### What is the current behavior?
When I run `web-ext run` in offline [WiFi is not connected], I'm getting the error.
```
run: Error: getaddrinfo ENOENT localhost:6005
    at Object.exports._errnoException (util.js:1022:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:91:26)

run: Error code: ENOENT
```
_NOTE: If I connect to No-Internet WiFi, **it's working as expected**._

### Version information (for bug reports)

* **Firefox version**:  57.0b1 (64-bit)
* **Your OS and version**: Windows 10 (64bit)
* **node --version** : v8.1.4
* **npm --version** : 5.0.3
* **web-ext --version**: 2.0.0

**Comment by kumar303** [comment]
Thanks for the bug report. Could you provide a log using `--verbose`? I'm not sure if this is happening in web-ext or Firefox.

**Comment by ritwickdey** [comment]
The Log

```
$ web-ext run --verbose

[program.js][debug] Getting the version from package.json
[program.js][info] Version: 2.0.0
[program.js][debug] Getting the version from package.json
[cmd/run.js][info] Running web extension from C:\Users\ritwick\Desktop\live-server-web-extension
[util/manifest.js][debug] Validating manifest at C:\Users\ritwick\Desktop\live-server-web-extension\manifest.json
[extension-runners/firefox-desktop.js][debug] Creating new Firefox profile
[firefox/index.js][debug] Running Firefox with profile at C:\Users\ritwick\AppData\Local\Temp\79ce19e1-f975-4415-b4fd-b91a5c0ef87d
[firefox/index.js][debug] Checking if remote Firefox port 6005 is available
[firefox/remote.js][debug] Connecting to Firefox on port 6005
[program.js][error]
run: Error: getaddrinfo ENOENT localhost:6005
    at Object._errnoException (util.js:1019:11)
    at errnoException (dns.js:58:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:95:26)

[program.js][error] run: Error code: ENOENT

```

**Comment by ritwickdey** [comment]
It connect my laptop to a wifi (even if no internet), it works perfectly fine

**Comment by ritwickdey** [comment]
I think, this issue is for binding `localhost`. not `127.0.01`.


https://github.com/nodejs/node/issues/726

[If this issue is small part, I would like to submit a PR :smile:]

**Comment by kumar303** [comment]
I see. Does changing it to `127.0.0.1` fix it? I can review the patch if you have time for it.

I don't think it's such a simple patch though. We use ﻿﻿use an external library to connect: https://github.com/mozilla/web-ext/blob/master/src/firefox/remote.js#L199

This external lib is only 24 lines long so I don't know why we use it, heh. We could copy it into web-ext. It doesn't appear to allow you to change the host.

Changing the host should be possible: https://github.com/mozilla/node-firefox-connect/blob/master/index.js

**Comment by ritwickdey** [comment]
Is there have any want to change `127.0.0.1` through CLI ? I don't think.
