### ISSUE TITLE
[webpack --watch + web-ext start] Unexpected packet from actor root

### ISSUE THREAD

**Issue by osdiab** [mozilla/web-ext#1092]
### Is this a feature request or a bug?
Bug

### What is the current behavior?
I am developing an extension. It uses `webpack@3.5.5` to compile a TypeScript project to JS scripts specified in `manifest.json`. For the development workflow I use the `concurrently@3.5.0` library to run the following command:

```
concurrently 'webpack --watch' 'web-ext run'
```

This starts up properly, but pretty frequently, the Firefox browser to boots up closes automatically and this error shows up in the terminal:

```
[1] /Users/omar/code/personal/webextension-max-tabs/node_modules/firefox-client/lib/client.js:173
[1]       throw new Error("Unexpected packet from actor " +  message.from
[1]             ^
[1] Error: Unexpected packet from actor root{"from":"root","addons":[{"actor":"server1.conn0.addon7","id":"aushelper@mozilla.org","name":"Application Update Service Helper","iconURL":null,"debuggable":true,"temporarilyInstalled":false,"consoleActor":"server1.conn0.addonConsole19","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server1.conn0.addon8","id":"e10srollout@mozilla.org","name":"Multi-process staged rollout","iconURL":null,"debuggable":true,"temporarilyInstalled":false,"consoleActor":"server1.conn0.addonConsole20","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server1.conn0.addon9","id":"firefox@getpocket.com","name":"Pocket","iconURL":null,"debuggable":true,"temporarilyInstalled":false,"consoleActor":"server1.conn0.addonConsole21","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server1.conn0.addon10","id":"screenshots@mozilla.org","name":"Firefox Screenshots","iconURL":null,"debuggable":true,"temporarilyInstalled":false,"consoleActor":"server1.conn0.addonConsole22","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server1.conn0.addon11","id":"webcompat@mozilla.org","name":"Web Compat","iconURL":null,"debuggable":true,"temporarilyInstalled":false,"consoleActor":"server1.conn0.addonConsole23","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server1.conn0.addon12","id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","name":"Default","iconURL":"chrome://browser/content/default-theme-icon.svg","temporarilyInstalled":false,"consoleActor":"server1.conn0.addonConsole24","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server1.conn0.webExtension13","url":"file:///Users/omar/code/personal/webextension-max-tabs/","outerWindowID":3,"consoleActor":"server1.conn0.consoleActor25","inspectorActor":"server1.conn0.inspectorActor26","callWatcherActor":"server1.conn0.callWatcherActor27","canvasActor":"server1.conn0.canvasActor28","webglActor":"server1.conn0.webglActor29","webaudioActor":"server1.conn0.webaudioActor30","styleSheetsActor":"server1.conn0.styleSheetsActor31","styleEditorActor":"server1.conn0.styleEditorActor32","storageActor":"server1.conn0.storageActor33","gcliActor":"server1.conn0.gcliActor34","memoryActor":"server1.conn0.memoryActor35","framerateActor":"server1.conn0.framerateActor36","eventLoopLagActor":"server1.conn0.eventLoopLagActor37","reflowActor":"server1.conn0.reflowActor38","cssPropertiesActor":"server1.conn0.cssPropertiesActor39","cssUsageActor":"server1.conn0.cssUsageActor40","monitorActor":"server1.conn0.monitorActor41","timelineActor":"server1.conn0.timelineActor42","directorManagerActor":"server1.conn0.directorManagerActor43","profilerActor":"server1.conn0.profilerActor44","performanceActor":"server1.conn0.performanceActor45","animationsActor":"server1.conn0.animationsActor46","promisesActor":"server1.conn0.promisesActor47","performanceEntriesActor":"server1.conn0.performanceEntriesActor48","emulationActor":"server1.conn0.emulationActor49","webExtensionInspectedWindowActor":"server1.conn0.webExtensionInspectedWindowActor50","id":"560311d46e1534d795c8ae440a7aac7729d04a2c@temporary-addon","name":"Tab Limit","iconURL":"file:///Users/omar/code/personal/webextension-max-tabs/icons/48.svg","debuggable":true,"temporarilyInstalled":true,"isWebExtension":true},{"actor":"server1.conn0.addon14","id":"firefox-compact-light@mozilla.org@personas.mozilla.org","name":"Compact Light","iconURL":"resource:///chrome/browser/content/browser/defaultthemes/compactlight.icon.svg","consoleActor":"server1.conn0.addonConsole51","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server1.conn0.addon15","id":"firefox-compact-dark@mozilla.org@personas.mozilla.org","name":"Compact Dark","iconURL":"resource:///chrome/browser/content/browser/defaultthemes/compactdark.icon.svg","consoleActor":"server1.conn0.addonConsole52","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server1.conn0.addon18","id":"{6c05dc9d-bf02-9ece-49d3-30aba1586653}","name":"Shockwave Flash","consoleActor":"server1.conn0.addonConsole55","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server1.conn0.addon56","id":"gmp-gmpopenh264","name":"OpenH264 Video Codec provided by Cisco Systems, Inc.","consoleActor":"server1.conn0.addonConsole58","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server1.conn0.addon57","id":"gmp-widevinecdm","name":"Widevine Content Decryption Module provided by Google Inc.","consoleActor":"server1.conn0.addonConsole59","traits":{"highlightable":false,"networkMonitor":false}}]}
[1]     at Client.handleMessage (/Users/omar/code/personal/webextension-max-tabs/node_modules/firefox-client/lib/client.js:173:13)
[1]     at Client.readMessage (/Users/omar/code/personal/webextension-max-tabs/node_modules/firefox-client/lib/client.js:220:10)
[1]     at Client.onData (/Users/omar/code/personal/webextension-max-tabs/node_modules/firefox-client/lib/client.js:186:16)
[1]     at emitOne (events.js:115:13)
[1]     at Socket.emit (events.js:210:7)
[1]     at addChunk (_stream_readable.js:252:12)
[1]     at readableAddChunk (_stream_readable.js:239:11)
[1]     at Socket.Readable.push (_stream_readable.js:197:10)
[1]     at TCP.onread (net.js:589:20)
[1] web-ext run exited with code 1
```

### Version information (for bug reports)

* **Firefox version**: 54.0.1 (64-bit)
* **Your OS and version**: 10.12.5 (16F73)
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````

```
v8.2.1
5.4.2
2.0.0
```

Thanks in advance!

**Comment by kumar303** [comment]
Hi. Thanks for the bug report. Could you attach a log generated with `web-ext run --verbose`?

As a side note, you may wish to [ignore your source files](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#--ignore-files_-i) so that only the final webpack-built files will trigger `web-ext` to reload your extension. However, that may not be related to this bug.

**Comment by osdiab** [comment]
I added my source files to be ignored, but the error still occurred; here's the verbose error:

```
[1] [watcher.js][debug] Last change detection: 16:52:22 GMT+0900 (JST)
[1] [extension-runners/index.js][debug] Reloading add-on at /Users/omar/code/personal/webextension-max-tabs
[1] [util/file-filter.js][debug] Resolved path /Users/omar/code/personal/webextension-max-tabs/__build/background.js with sourceDir /Users/omar/code/personal/webextension-max-tabs to /Users/omar/code/personal/webextension-max-tabs/__build/background.js
[1] [watcher.js][debug] Changed: /Users/omar/code/personal/webextension-max-tabs/__build/background.js
[1] [watcher.js][debug] Last change detection: 16:52:22 GMT+0900 (JST)
[1] [util/file-filter.js][debug] Resolved path /Users/omar/code/personal/webextension-max-tabs/__build/options_ui.js with sourceDir /Users/omar/code/personal/webextension-max-tabs to /Users/omar/code/personal/webextension-max-tabs/__build/options_ui.js
[1] [watcher.js][debug] Changed: /Users/omar/code/personal/webextension-max-tabs/__build/options_ui.js
[1] [watcher.js][debug] Last change detection: 16:52:27 GMT+0900 (JST)
[1] [extension-runners/index.js][debug] Reloading add-on at /Users/omar/code/personal/webextension-max-tabs
[1] [firefox/index.js][debug] Firefox stdout: 1507708347648	addons.xpi	WARN	Addon with ID 9ee831049cf849a01eb60d15c3bec1fa6d3ee704@temporary-addon already installed, older version will be disabled
[1]
[1] /Users/omar/code/personal/webextension-max-tabs/node_modules/firefox-client/lib/client.js:173
[1]       throw new Error("Unexpected packet from actor " +  message.from
[1]             ^
[1] Error: Unexpected packet from actor root{"from":"root","addons":[{"actor":"server1.conn0.addon7","id":"aushelper@mozilla.org","name":"Application Update Service Helper","iconURL":null,"debuggable":true,"temporarilyInstalled":false,"consoleActor":"server1.conn0.addonConsole19","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server1.conn0.addon8","id":"e10srollout@mozilla.org","name":"Multi-process staged rollout","iconURL":null,"debuggable":true,"temporarilyInstalled":false,"consoleActor":"server1.conn0.addonConsole20","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server1.conn0.addon9","id":"firefox@getpocket.com","name":"Pocket","iconURL":null,"debuggable":true,"temporarilyInstalled":false,"consoleActor":"server1.conn0.addonConsole21","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server1.conn0.addon10","id":"screenshots@mozilla.org","name":"Firefox Screenshots","iconURL":null,"debuggable":true,"temporarilyInstalled":false,"consoleActor":"server1.conn0.addonConsole22","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server1.conn0.addon11","id":"webcompat@mozilla.org","name":"Web Compat","iconURL":null,"debuggable":true,"temporarilyInstalled":false,"consoleActor":"server1.conn0.addonConsole23","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server1.conn0.addon12","id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","name":"Default","iconURL":"chrome://browser/content/default-theme-icon.svg","temporarilyInstalled":false,"consoleActor":"server1.conn0.addonConsole24","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server1.conn0.webExtension13","url":"file:///Users/omar/code/personal/webextension-max-tabs/","outerWindowID":12,"consoleActor":"server1.conn0.consoleActor25","inspectorActor":"server1.conn0.inspectorActor26","callWatcherActor":"server1.conn0.callWatcherActor27","canvasActor":"server1.conn0.canvasActor28","webglActor":"server1.conn0.webglActor29","webaudioActor":"server1.conn0.webaudioActor30","styleSheetsActor":"server1.conn0.styleSheetsActor31","styleEditorActor":"server1.conn0.styleEditorActor32","storageActor":"server1.conn0.storageActor33","gcliActor":"server1.conn0.gcliActor34","memoryActor":"server1.conn0.memoryActor35","framerateActor":"server1.conn0.framerateActor36","eventLoopLagActor":"server1.conn0.eventLoopLagActor37","reflowActor":"server1.conn0.reflowActor38","cssPropertiesActor":"server1.conn0.cssPropertiesActor39","cssUsageActor":"server1.conn0.cssUsageActor40","monitorActor":"server1.conn0.monitorActor41","timelineActor":"server1.conn0.timelineActor42","directorManagerActor":"server1.conn0.directorManagerActor43","profilerActor":"server1.conn0.profilerActor44","performanceActor":"server1.conn0.performanceActor45","animationsActor":"server1.conn0.animationsActor46","promisesActor":"server1.conn0.promisesActor47","performanceEntriesActor":"server1.conn0.performanceEntriesActor48","emulationActor":"server1.conn0.emulationActor49","webExtensionInspectedWindowActor":"server1.conn0.webExtensionInspectedWindowActor50","id":"9ee831049cf849a01eb60d15c3bec1fa6d3ee704@temporary-addon","name":"Tab Limit","iconURL":"file:///Users/omar/code/personal/webextension-max-tabs/icons/48.svg","debuggable":true,"temporarilyInstalled":true,"isWebExtension":true},{"actor":"server1.conn0.addon14","id":"firefox-compact-light@mozilla.org@personas.mozilla.org","name":"Compact Light","iconURL":"resource:///chrome/browser/content/browser/defaultthemes/compactlight.icon.svg","consoleActor":"server1.conn0.addonConsole51","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server1.conn0.addon15","id":"firefox-compact-dark@mozilla.org@personas.mozilla.org","name":"Compact Dark","iconURL":"resource:///chrome/browser/content/browser/defaultthemes/compactdark.icon.svg","consoleActor":"server1.conn0.addonConsole52","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server1.conn0.addon16","id":"gmp-gmpopenh264","name":"OpenH264 Video Codec provided by Cisco Systems, Inc.","consoleActor":"server1.conn0.addonConsole53","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server1.conn0.addon17","id":"gmp-widevinecdm","name":"Widevine Content Decryption Module provided by Google Inc.","consoleActor":"server1.conn0.addonConsole54","traits":{"highlightable":false,"networkMonitor":false}},{"actor":"server1.conn0.addon18","id":"{6c05dc9d-bf02-9ece-49d3-30aba1586653}","name":"Shockwave Flash","consoleActor":"server1.conn0.addonConsole55","traits":{"highlightable":false,"networkMonitor":false}}]}
[1]     at Client.handleMessage (/Users/omar/code/personal/webextension-max-tabs/node_modules/firefox-client/lib/client.js:173:13)
[1]     at Client.readMessage (/Users/omar/code/personal/webextension-max-tabs/node_modules/firefox-client/lib/client.js:220:10)
[1]     at Client.onData (/Users/omar/code/personal/webextension-max-tabs/node_modules/firefox-client/lib/client.js:186:16)
[1]     at emitOne (events.js:115:13)
[1]     at Socket.emit (events.js:210:7)
[1]     at addChunk (_stream_readable.js:252:12)
[1]     at readableAddChunk (_stream_readable.js:239:11)
[1]     at Socket.Readable.push (_stream_readable.js:197:10)
[1]     at TCP.onread (net.js:589:20)
[1] web-ext run --verbose --ignore-files src/**/* exited with code 1
```

Thanks for your prompt help! I'm traveling around so I just got around to posting this now.

**Comment by osdiab** [comment]
And also to be clearer, this doesn't happen everytime—just frequently enough to be a pain; sometimes it happens almost every time/every other time I save my source and therefore trigger Webpack to regenerate my code again but for instance right now it's only happening once in maybe 10-15 saves or so, I don't really know why the frequency of the error varies so much.

**Comment by sneakypete81** [comment]
I see this behaviour too on both Mac and Windows, usually failing but occasionally succeeding. It appears to be if a file changes at some critical point while Firefox is starting up - if I add a fixed delay to ensure webpack doesn't output anything while `web-ext run` is starting, it never seems to fail.

See also #1069.

**Firefox version:** 56.0.1 (64-bit)
**OS and version:** Win10 RS1

    node --version && npm --version && web-ext --version
    v6.10.1
    3.10.10
    1.9.1

**Comment by kumar303** [comment]
Thanks for the verbose log. It looks like 'Application Update Service Helper' is maybe causing the issue but things like that are supposed to be [disabled by web-ext](https://github.com/mozilla/web-ext/blob/master/src/firefox/preferences.js#L55). Maybe some configuration for it changed.

Also, maybe we should not throw an error for unexpected actor messages. I'll have to think about the implications of ignoring errors though.

**Comment by kumar303** [comment]
Fixing this may require porting from `firefox-client` to https://github.com/saucelabs/foxdriver (or something)
