### ISSUE TITLE
Running web-ext run gives me syntax error

### ISSUE THREAD

**Issue by jonathan-s** [mozilla/web-ext#1117]
### Is this a feature request or a bug?
It's a bug. 

### What is the current behavior?
```
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/web-ext/node_modules/whatwg-url/lib/public-api.js:3:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```
Running `web-ext run`

### Version information (for bug reports)

* **Firefox version**:
* **Your OS and version**: OSX
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````

v5.6.0
5.5.1
And the last command throws the same error.

**Comment by jonathan-s** [comment]
Installing later versions of node etc solved the problem.
