### ISSUE TITLE
Cannot start firefox with a profile including large number of tabs

### ISSUE THREAD

**Issue by piroor** [mozilla/web-ext#1133]
### Is this a feature request or a bug?

Bug, due to a problem of depending library `firefox-client`. See also the issue reported to the library https://github.com/harthur/firefox-client/issues/15 and a pull request https://github.com/harthur/firefox-client/pull/16

### What is the current behavior?

When I try to start Firefox 57 with a session including large number of tabs via the tool, I got "Unexpected packet from actor ..." and Firefox cannot be started. Steps to reproduce:

 1. Install web-ext, like `npm install -g web-ext`.
 2. Start Firefox 57, set to restore all tabs and windows on the next startup, and shutdown.
 3. Copy the Firefox's profile to another location.
 4. Start Firefox 57 via web-ext, like: `web-ext run --firefox="C:\path\to\firefox" --keep-profile-changes --firefox-profile=C:\path\to\profile\with\large-number-tabs\copied\at\step3 --source-dir=C:\path\to\addon\repository`

Then Firefox starts but suddenly shutdown. In the console, an error is reported:

```
WebExtError: Temporary add-on installation is not supported in this version of Firefox (you need Firefox 49 or higher). For older Firefox versions, use --pre-install
    at FirefoxDesktopExtensionRunner._callee6$ (C:\Users\piro\AppData\Roaming\npm\node_modules\web-ext\dist\webpack:\src\extension-runners\firefox-desktop.js:288:19)
    at tryCatch (C:\Users\piro\AppData\Roaming\npm\node_modules\web-ext\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\piro\AppData\Roaming\npm\node_modules\web-ext\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as throw] (C:\Users\piro\AppData\Roaming\npm\node_modules\web-ext\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\piro\AppData\Roaming\npm\node_modules\web-ext\dist\webpack:\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:1)
    at C:\Users\piro\AppData\Roaming\npm\node_modules\web-ext\dist\webpack:\node_modules\babel-runtime\helpers\asyncToGenerator.js:30:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### What is the expected or desired behavior?

Firefox starts and the specified addon is loaded as a temporary addon.

### Version information (for bug reports)

* **Firefox version**: Firefox 57
* **Your OS and version**: Windows 10 Creators Update
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
v8.9.1
5.5.1
````

**Comment by kumar303** [comment]
Hmm, this looks similar to https://github.com/mozilla/web-ext/issues/1092 but it might be a different actor event.

Can you attach a verbose log?

Your proposed fix in https://github.com/harthur/firefox-client/pull/16 seems reasonable but unfortunately that library is unmaintained. We might need to pull the code directly into `web-ext` or make a fork.

**Comment by piroor** [comment]
Did you mean an output with `-v` option? I retried with the latest master:

```
C:\Users\piro\codes\web-ext-orig>node bin\web-ext run --firefox="C:\Program Files\Mozilla Firefox\firefox.exe" --keep-profile-changes --firefox-profile=C:\Users\piro\AppData\Roaming\Mozilla\Firefox\Profiles\nightly2 --source-dir=C:\Users\Public\Data\codes\treestyletab\webextensions -v
[..\..\..\Public\Data\codes\web-ext-orig\src\program.js][debug] Getting version from the git revision
[..\..\..\Public\Data\codes\web-ext-orig\src\program.js][info] Version: master-a55ee4c9ef59c590f0016be7984ac7ca63b27ea0
[..\..\..\Public\Data\codes\web-ext-orig\src\cmd\run.js][info] Running web extension from C:\Users\Public\Data\codes\treestyletab\webextensions
[..\..\..\Public\Data\codes\web-ext-orig\src\util\manifest.js][debug] Validating manifest at C:\Users\Public\Data\codes\treestyletab\webextensions\manifest.json
[..\..\..\Public\Data\codes\web-ext-orig\src\extension-runners\firefox-desktop.js][debug] Using Firefox profile from C:\Users\piro\AppData\Roaming\Mozilla\Firefox\Profiles\nightly2
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\index.js][debug] Running Firefox with profile at C:\Users\piro\AppData\Roaming\Mozilla\Firefox\Profiles\nightly2
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\index.js][debug] Checking if remote Firefox port 6005 is available
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\remote.js][debug] Connecting to Firefox on port 6005
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\remote.js][debug] Connected to the remote Firefox debugger on port 6005
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\index.js][debug] Remote Firefox port 6005 is in use (retries remaining: 10)
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\remote.js][debug] Connecting to Firefox on port 6006
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\remote.js][debug] Received "end" from Firefox client
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\index.js][debug] Executing Firefox binary: C:\Program Files\Mozilla Firefox\firefox.exe
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\index.js][debug] Firefox args: -start-debugger-server 6006 -foreground -no-remote -profile C:\Users\piro\AppData\Roaming\Mozilla\Firefox\Profiles\nightly2
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\index.js][info] Use --verbose or open Tools > Web Developer > Browser Console to see logging
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\remote.js][debug] Connecting to the remote Firefox debugger
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\remote.js][debug] Connecting to Firefox on port 6006
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\index.js][debug] Firefox stderr: JavaScript strict warning: resource://gre/modules/addons/XPIProvider.jsm, line 1579: ReferenceError: reference to undefined property "app-temporary"
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\index.js][debug] Firefox stdout: Started debugger server on 6006
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\index.js][debug] Firefox stderr: Unable to read VR Path Registry from C:\Users\piro\AppData\Local\openvr\openvrpaths.vrpath
JavaScript strict warning: resource://gre/modules/TelemetryEnvironment.jsm, line 711: ReferenceError: reference to undefined property "isActive"
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\index.js][debug] Firefox stderr: JavaScript strict warning: resource:///modules/CustomizableUI.jsm, line 2476: ReferenceError: reference to undefined property "disabled"
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\index.js][debug] Firefox stdout: 1510843220518     addons.webextension.Tab-Session-Manager@sienori WARN    Please specify whether you want browser_style or not in your browser_action options.
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\remote.js][debug] Connected to the remote Firefox debugger on port 6006
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\index.js][debug] Firefox stderr: JavaScript strict warning: resource://gre/modules/LightweightThemeConsumer.jsm, line 154: ReferenceError: reference to undefined property "additionalBackgrounds"
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\index.js][debug] Firefox stderr: JavaScript strict warning: resource://gre/modules/LightweightThemeConsumer.jsm, line 197: ReferenceError: reference to undefined property "backgroundsAlignment"
JavaScript strict warning: chrome://browser/content/tabbrowser.xml, line 739: ReferenceError: reference to undefined property "initialPageLoadedFromURLBar"
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\index.js][debug] Firefox stderr: JavaScript strict warning: resource://devtools/shared/security/socket.js, line 781: ReferenceError: reference to undefined property "_handshakeTimeout"
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\index.js][debug] Firefox stderr: JavaScript strict warning: resource:///modules/CustomizableUI.jsm, line 1506: ReferenceError: reference to undefined property "viewId"
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\index.js][debug] Firefox stderr: JavaScript strict warning: resource://gre/modules/ProfileAge.jsm, line 203: ReferenceError: reference to undefined property "reset"
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\index.js][debug] Firefox stderr: Unable to read VR Path Registry from C:\Users\piro\AppData\Local\openvr\openvrpaths.vrpath
JavaScript strict warning: moz-extension://7b194e0d-6fd2-40d5-be38-3a50e7f517f7/background.js, line 320: ReferenceError: assignment to undeclared variable tabList
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\index.js][debug] Firefox stderr: JavaScript strict warning: resource://gre/modules/PushService.jsm, line 23: ReferenceError: reference to undefined property "getCryptoParams"
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\index.js][debug] Firefox stderr: JavaScript strict warning: resource://devtools/shared/node-properties/node-properties.js, line 134: ReferenceError: reference to undefined property "resume"
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\index.js][debug] Firefox stderr: JavaScript strict warning: resource://devtools/shared/node-properties/node-properties.js, line 124: ReferenceError: reference to undefined property "o"
JavaScript strict warning: resource://devtools/shared/node-properties/node-properties.js, line 130: ReferenceError: reference to undefined property "o"
[..\..\..\Public\Data\codes\web-ext-orig\src\firefox\remote.js][debug] listTabs returned a falsey addonsActor: undefined
[..\..\..\Public\Data\codes\web-ext-orig\src\extension-runners\firefox-desktop.js][debug] Caught: RemoteTempInstallNotSupported: This is an older version of Firefox that does not provide an add-ons actor for remote installation. Try Firefox 49 or higher.
[..\..\..\Public\Data\codes\web-ext-orig\src\program.js][error]
WebExtError: Temporary add-on installation is not supported in this version of Firefox (you need Firefox 49 or higher). For older Firefox versions, use --pre-install
    at FirefoxDesktopExtensionRunner._callee6$ (C:\Users\Public\Data\codes\web-ext-orig\dist\webpack:\Public\Data\codes\web-ext-orig\src\extension-runners\firefox-desktop.js:273:19)
    at tryCatch (C:\Users\Public\Data\codes\web-ext-orig\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\Public\Data\codes\web-ext-orig\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as throw] (C:\Users\Public\Data\codes\web-ext-orig\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\Public\Data\codes\web-ext-orig\dist\webpack:\C:\Users\Public\Data\codes\web-ext-orig\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:1)
    at C:\Users\Public\Data\codes\web-ext-orig\dist\webpack:\C:\Users\Public\Data\codes\web-ext-orig\node_modules\babel-runtime\helpers\asyncToGenerator.js:30:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

[..\..\..\Public\Data\codes\web-ext-orig\src\program.js][debug] Command executed: run

C:\Users\piro\codes\web-ext-orig>
```

In this case I copied sessionstore.jsonlz4 from a profile with 50 or 60 pinned tabs. Note that you need to pin all tabs because `web-ext run` doesn't restore unpinned tabs on the startup.

**Comment by piroor** [comment]
To be honest I got this problem on dogfooding of my addon with a little bit modified version of `web-ext`. Because I need to test my addon with large number of tabs, I modified `web-ext` to restore tabs on the startup (by removing some codes to override Firefox's startup preferences). So in regular use case this problem won't happen.

**Comment by kumar303** [comment]
Thanks for the verbose log, I'll take a closer look shortly.
 
I wanted to add a note to myself that there is a maintained library we could use to replace `firefox-client` : https://github.com/saucelabs/foxdriver

**Comment by MarZab** [comment]
This happened to me as well with a corrupted profile, had to run it manually a couple of times before it recovered enough to be able to use it with web-ext again. The error message is missleading.
