### ISSUE TITLE
`web-ext run` crashes

### ISSUE THREAD

**Issue by nchevobbe** [mozilla/web-ext#1141]
### Is this a feature request or a bug?
Bug

### What is the current behavior?
I have an extension where I use web-ext with webpack, which I run using the following command in my package.json `
```json
scripts: {
  "start:firefox": "webpack --watch --colors & web-ext run"
}
```

This works quite well and new webpack builds get picked up by web-ext.
But, from time to time, web-ext crashes with the following error: 

```bash
Last extension reload: 22:55:44 GMT+0100 (CET)
/Users/nicolaschevobbe/Projects/tabspace/node_modules/firefox-client/lib/client.js:173
      throw new Error("Unexpected packet from actor " +  message.from
            ^
Error: Unexpected packet from actor root [0]
    at Client.handleMessage (/Users/nicolaschevobbe/Projects/tabspace/node_modules/firefox-client/lib/client.js:173:13)
    at Client.readMessage (/Users/nicolaschevobbe/Projects/tabspace/node_modules/firefox-client/lib/client.js:220:10)
    at Client.onData (/Users/nicolaschevobbe/Projects/tabspace/node_modules/firefox-client/lib/client.js:186:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

I am not sure this is related to webpack.

---

[0]:
```json
{
  "from": "root",
  "addons": [
    {
      "actor": "server2.conn0.addon8",
      "id": "onboarding@mozilla.org",
      "name": "Photon onboarding",
      "iconURL": null,
      "debuggable": true,
      "temporarilyInstalled": false,
      "consoleActor": "server2.conn0.addonConsole25",
      "traits": {
        "highlightable": false,
        "networkMonitor": false
      }
    },
    {
      "actor": "server2.conn0.addon9",
      "id": "e10srollout@mozilla.org",
      "name": "Multi-process staged rollout",
      "iconURL": null,
      "debuggable": true,
      "temporarilyInstalled": false,
      "consoleActor": "server2.conn0.addonConsole26",
      "traits": {
        "highlightable": false,
        "networkMonitor": false
      }
    },
    {
      "actor": "server2.conn0.addon10",
      "id": "webcompat@mozilla.org",
      "name": "Web Compat",
      "iconURL": null,
      "debuggable": true,
      "temporarilyInstalled": false,
      "consoleActor": "server2.conn0.addonConsole27",
      "traits": {
        "highlightable": false,
        "networkMonitor": false
      }
    },
    {
      "actor": "server2.conn0.addon11",
      "id": "aushelper@mozilla.org",
      "name": "Application Update Service Helper",
      "iconURL": null,
      "debuggable": true,
      "temporarilyInstalled": false,
      "consoleActor": "server2.conn0.addonConsole28",
      "traits": {
        "highlightable": false,
        "networkMonitor": false
      }
    },
    {
      "actor": "server2.conn0.addon12",
      "id": "formautofill@mozilla.org",
      "name": "Form Autofill",
      "iconURL": null,
      "debuggable": true,
      "temporarilyInstalled": false,
      "consoleActor": "server2.conn0.addonConsole29",
      "traits": {
        "highlightable": false,
        "networkMonitor": false
      }
    },
    {
      "actor": "server2.conn0.addon13",
      "id": "firefox@getpocket.com",
      "name": "Pocket",
      "iconURL": null,
      "debuggable": true,
      "temporarilyInstalled": false,
      "consoleActor": "server2.conn0.addonConsole30",
      "traits": {
        "highlightable": false,
        "networkMonitor": false
      }
    },
    {
      "actor": "server2.conn0.addon14",
      "id": "shield-recipe-client@mozilla.org",
      "name": "Shield Recipe Client",
      "iconURL": null,
      "debuggable": true,
      "temporarilyInstalled": false,
      "consoleActor": "server2.conn0.addonConsole31",
      "traits": {
        "highlightable": false,
        "networkMonitor": false
      }
    },
    {
      "actor": "server2.conn0.addon15",
      "id": "screenshots@mozilla.org",
      "name": "Firefox Screenshots",
      "iconURL": null,
      "debuggable": true,
      "temporarilyInstalled": false,
      "consoleActor": "server2.conn0.addonConsole32",
      "traits": {
        "highlightable": false,
        "networkMonitor": false
      }
    },
    {
      "actor": "server2.conn0.addon16",
      "id": "activity-stream@mozilla.org",
      "name": "Activity Stream",
      "iconURL": null,
      "debuggable": true,
      "temporarilyInstalled": false,
      "consoleActor": "server2.conn0.addonConsole33",
      "traits": {
        "highlightable": false,
        "networkMonitor": false
      }
    },
    {
      "actor": "server2.conn0.addon17",
      "id": "followonsearch@mozilla.com",
      "name": "Follow-on Search Telemetry",
      "iconURL": null,
      "debuggable": true,
      "temporarilyInstalled": false,
      "consoleActor": "server2.conn0.addonConsole34",
      "traits": {
        "highlightable": false,
        "networkMonitor": false
      }
    },
    {
      "actor": "server2.conn0.addon18",
      "id": "{972ce4c6-7e08-4474-a285-3208198ce6fd}",
      "name": "Thème par défaut",
      "iconURL": "chrome://browser/content/default-theme-icon.svg",
      "temporarilyInstalled": false,
      "consoleActor": "server2.conn0.addonConsole35",
      "traits": {
        "highlightable": false,
        "networkMonitor": false
      }
    },
    {
      "actor": "server2.conn0.webExtensionAddon19",
      "id": "cca9b2f9e611d9d5dd788aff7b002e645b1e0e55@temporary-addon",
      "name": "TabSpace",
      "url": "file:///Users/nicolaschevobbe/Projects/tabspace/",
      "iconURL": "file:///Users/nicolaschevobbe/Projects/tabspace/icons/tabspace.svg",
      "debuggable": true,
      "temporarilyInstalled": true,
      "isWebExtension": true,
      "manifestURL": "moz-extension://eb095fb2-124a-4143-a45a-2e7abddde296/manifest.json",
      "warnings": []
    },
    {
      "actor": "server2.conn0.addon20",
      "id": "firefox-compact-light@mozilla.org@personas.mozilla.org",
      "name": "Clair",
      "iconURL": "resource:///chrome/browser/content/browser/defaultthemes/light.icon.svg",
      "consoleActor": "server2.conn0.addonConsole36",
      "traits": {
        "highlightable": false,
        "networkMonitor": false
      }
    },
    {
      "actor": "server2.conn0.addon21",
      "id": "firefox-compact-dark@mozilla.org@personas.mozilla.org",
      "name": "Sombre",
      "iconURL": "resource:///chrome/browser/content/browser/defaultthemes/dark.icon.svg",
      "consoleActor": "server2.conn0.addonConsole37",
      "traits": {
        "highlightable": false,
        "networkMonitor": false
      }
    },
    {
      "actor": "server2.conn0.addon22",
      "id": "gmp-gmpopenh264",
      "name": "Codec vidéo OpenH264 fourni par Cisco Systems, Inc.",
      "consoleActor": "server2.conn0.addonConsole38",
      "traits": {
        "highlightable": false,
        "networkMonitor": false
      }
    },
    {
      "actor": "server2.conn0.addon23",
      "id": "gmp-widevinecdm",
      "name": "Module de déchiffrement de contenu Widevine fourni par Google Inc.",
      "consoleActor": "server2.conn0.addonConsole39",
      "traits": {
        "highlightable": false,
        "networkMonitor": false
      }
    },
    {
      "actor": "server2.conn0.addon24",
      "id": "Shockwave FlashShockwave Flash 25.0 r0",
      "name": "Shockwave Flash",
      "consoleActor": "server2.conn0.addonConsole40",
      "traits": {
        "highlightable": false,
        "networkMonitor": false
      }
    }
  ]
}
```

### What is the expected or desired behavior?
web-ext should not crash

### Version information (for bug reports)

* **Firefox version**: 57.0
* **Your OS and version**: OSX 10.11.6 (15G17023)
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
- node: `v7.2.1`
- npm: `5.5.1`
- web-ext: `2.2.2`

**Comment by kumar303** [comment]
Hi. Thanks for taking the time to file an issue. We're tracking it in https://github.com/mozilla/web-ext/issues/1092 but your extra info about running actors will be helpful.
