### ISSUE TITLE
webExt.cmd.sign returns "TypeError: path must be a string or Buffer"

### ISSUE THREAD

**Issue by helfi92** [mozilla/web-ext#1146]
### Is this a feature request or a bug?
bug

### What is the current behavior?
When I run the `sign` command programmatically, I get a weird error `TypeError: path must be a string or Buffer`.

```js
const webExt = require('web-ext').default;

webExt.cmd.sign({
  sourceDir: 'build/',
  apiKey: 'test',
  apiSecret: 'test'
});
```
For this example I used a bad api keys. I assume the `sign` method will not work even if proper keys are provided.

### What is the expected or desired behavior?
The expected behavior should be akin to when running from the command line.

```bash
 web-ext sign --api-key='test' --api-secret='test' --source-dir='build/'
```
returns `Error: Received bad response from the server while requesting https://addons.mozilla.org/api/v3/addons/` which is what I expect to see.

### Version information (for bug reports)

* **Firefox version**:
58.0b9 (64-bit)
* **Your OS and version**:
macOS Sierra 10.12.6
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````

node: v8.2.1
npm: 5.5.1
web-ext: 2.2.2

**Comment by kumar303** [comment]
Could you turn on verbose logging before calling `webExt.cmd.sign()` and provide the output?

**Comment by helfi92** [comment]
@kumar303 

Using:

```js
webExt.cmd.sign({
  sourceDir: 'build/',
  apiKey: 'test',
  apiSecret: 'test'
});
```

Returns: 

```bash
[cmd/run.js][info] Running web extension from /Users/haali/Desktop/webextension-neutrino-test/build
[util/manifest.js][debug] Validating manifest at /Users/haali/Desktop/webextension-neutrino-test/build/manifest.json
[util/temp-dir.js][debug] Created temporary directory: /var/folders/7l/zy8zfdn14wv1h5lj6lvpzc940000gn/T/tmp-web-ext-26471L3Yy0om5Qpo4
[util/temp-dir.js][debug] Removing temporary directory: /var/folders/7l/zy8zfdn14wv1h5lj6lvpzc940000gn/T/tmp-web-ext-26471L3Yy0om5Qpo4

TypeError: path must be a string or Buffer
    at Object.fs.stat (fs.js:936:11)
    at Object.<anonymous> (/Users/haali/Documents/Mozilla/projects/neutrino-dev/node_modules/graceful-fs/polyfills.js:283:17)
    at eval (eval at thenify.withCallback (/Users/haali/Documents/Mozilla/projects/neutrino-dev/node_modules/thenify/index.js:33:10), <anonymous>:12:12)
    at Promise (<anonymous>)
    at Object.eval (eval at thenify.withCallback (/Users/haali/Documents/Mozilla/projects/neutrino-dev/node_modules/thenify/index.js:33:10), <anonymous>:10:8)
    at _callee$ (/Users/haali/Documents/Mozilla/projects/neutrino-dev/node_modules/web-ext/dist/webpack:/src/util/artifacts.js:21:28)
    at tryCatch (/Users/haali/Documents/Mozilla/projects/neutrino-dev/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/haali/Documents/Mozilla/projects/neutrino-dev/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/haali/Documents/Mozilla/projects/neutrino-dev/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/haali/Documents/Mozilla/projects/neutrino-dev/node_modules/web-ext/dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:1)
    at /Users/haali/Documents/Mozilla/projects/neutrino-dev/node_modules/web-ext/dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:1
    at Promise (<anonymous>)
    at F (/Users/haali/Documents/Mozilla/projects/neutrino-dev/node_modules/web-ext/dist/webpack:/node_modules/core-js/library/modules/_export.js:35:1)
    at /Users/haali/Documents/Mozilla/projects/neutrino-dev/node_modules/web-ext/dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:1
    at prepareArtifactsDir (/Users/haali/Documents/Mozilla/projects/neutrino-dev/node_modules/web-ext/dist/web-ext.js:2964:17)
    at _callee$ (/Users/haali/Documents/Mozilla/projects/neutrino-dev/node_modules/web-ext/dist/webpack:/src/cmd/sign.js:71:13)
error Command failed with exit code 1.
```

**Comment by kumar303** [comment]
ok, I see. It's because you did not specify `artifactsDir`. You can look at the type definition of [`run`](https://github.com/mozilla/web-ext/blob/67a296840028a127a466c5c0113e3712be1ffff9/src/cmd/run.js#L24) to see all of the parameters you must specify.

Unfortunately, we don't have argument validation implemented for programmatic use of `webExt`. We only have it implemented at the program level (via the CLI parser). Since this is a known limitation which is [documented as such](https://github.com/mozilla/web-ext/#using-web-ext-in-nodejs-code), I'm closing the issue.

However, feel free to open a new issue about adding argument validation to `run` and other functions. I wouldn't be opposed to a patch but it would be nice to connect it with the existing validation so that we don't have a duplication of validation code.

**Comment by kumar303** [comment]
Whoops, I meant check the type of arguments required by [`sign`](https://github.com/mozilla/web-ext/blob/67a296840028a127a466c5c0113e3712be1ffff9/src/cmd/sign.js#L22).

**Comment by helfi92** [comment]
@kumar303 My issue is with the `sign` command, not the `run` command.

**Comment by helfi92** [comment]
I assume I still need to supply the `artifactsDir` with the `sign` command according to its [definition](https://github.com/mozilla/web-ext/blob/67a296840028a127a466c5c0113e3712be1ffff9/src/cmd/sign.js#L27).

**Comment by kumar303** [comment]
I think it would be a good idea to add validation, even if it duplicates our CLI validation. I filed it as https://github.com/mozilla/web-ext/issues/1147

**Comment by helfi92** [comment]
Awesome! Thanks for the quick response.
