### ISSUE TITLE
Web-ext lint doesn't throw error on invalid manifest

### ISSUE THREAD

**Issue by laedit** [mozilla/web-ext#1150]
### Is this a feature request or a bug?
This is a bug.

### What is the current behavior?
When the manifest contains some invalid properties like:

``` json
"engine": {
      "version": "<=48.0a1"
    }
  }
```
(The whole sample manifest is in the [ziped attachment](https://github.com/mozilla/web-ext/files/1548155/manifest.zip))
`web-ext lint` returns the following:

```
Validation Summary:

errors          0
notices         0
warnings        0
```
But `web-ext run` fails with the following error:

```
Error: Extension is invalid
    at [USER]\AppData\Roaming\npm\node_modules\web-ext\dist\webpack:\src\firefox\remote.js:116:27
    at EventEmitter.handleMessage ([USER]\AppData\Roaming\npm\node_modules\web-ext\node_modules\firefox-client\lib\client.js:161:7)
    at EventEmitter.readMessage ([USER]\AppData\Roaming\npm\node_modules\web-ext\node_modules\firefox-client\lib\client.js:220:10)
    at EventEmitter.onData ([USER]\AppData\Roaming\npm\node_modules\web-ext\node_modules\firefox-client\lib\client.js:186:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)

[firefox-profile] cannot delete profileDir on exit [USER]\AppData\Local\Temp\bca18c49-f9fc-48f7-89a7-151e5b8e6359 { Error: EBUSY: resource busy or locked, unlink '[USER]\AppData\Local\Temp\bca18c49-f9fc-48f7-89a7-151e5b8e6359\cert8.db'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1104:18)
    at rimrafSync ([USER]\AppData\Roaming\npm\node_modules\web-ext\node_modules\fs-extra\lib\remove\rimraf.js:254:15)
    at options.readdirSync.forEach.f ([USER]\AppData\Roaming\npm\node_modules\web-ext\node_modules\fs-extra\lib\remove\rimraf.js:291:39)
    at Array.forEach (native)
    at rmkidsSync ([USER]\AppData\Roaming\npm\node_modules\web-ext\node_modules\fs-extra\lib\remove\rimraf.js:291:26)
    at rmdirSync ([USER]\AppData\Roaming\npm\node_modules\web-ext\node_modules\fs-extra\lib\remove\rimraf.js:283:7)
    at Function.rimrafSync [as sync] ([USER]\AppData\Roaming\npm\node_modules\web-ext\node_modules\fs-extra\lib\remove\rimraf.js:252:7)
    at Object.removeSync ([USER]\AppData\Roaming\npm\node_modules\web-ext\node_modules\fs-extra\lib\remove\index.js:6:17)
    at FirefoxProfile._cleanOnExit ([USER]\AppData\Roaming\npm\node_modules\web-ext\node_modules\firefox-profile\lib\firefox_profile.js:253:10)
  errno: -4082,
  code: 'EBUSY',
  syscall: 'unlink',
  path: '[USER]\\AppData\\Local\\Temp\\bca18c49-f9fc-48f7-89a7-151e5b8e6359\\cert8.db' }
```

### What is the expected or desired behavior?
`web-ext lint` should return an error if the manifest is invalid.

### Version information (for bug reports)

* **Firefox version**: tested on 59.0a1 and 56.0.1
* **Your OS and version**: tested on Windows 10 and Windows 8
* Paste the output of these commands:

````
node: v6.11.3
npm: 3.10.10
web-ext: 2.2.2
````

**Comment by kumar303** [comment]
Thanks for the bug report. Could you refile it in https://github.com/mozilla/addons-linter ?

**Comment by laedit** [comment]
It seems that you have already [opened one](https://github.com/mozilla/addons-linter/issues/1074), thanks for that! 😄 
And sorry for this one.
