### ISSUE TITLE
Crash when pref option is an array in config file

### ISSUE THREAD

**Issue by dessant** [mozilla/web-ext#1213]
### Is this a feature request or a bug?
bug

### What is the current behavior?
web-ext-config.js
```js
module.exports = {
  run: {
    pref: [
      'devtools.webconsole.persistlog=true',
      'extensions.webextensions.remote=true'
    ]
  }
};
```

```
$ web-ext run -s dist --verbose
[program.js][debug] Getting the version from package.json
[program.js][info] Version: 2.3.1
[program.js][debug] Getting the version from package.json
[program.js][debug] Discovering config files. Set --no-config-discovery to disable
[config.js][debug] Discovered config "/home/prc/.web-ext-config.js" does not exist or is not readable
[program.js][info] Applying config file: ./web-ext-config.js
[config.js][debug] Loading JS config file: "/media/s1/dev/pr/clear-browsing-data/web-ext-config.js" (resolved to "/media/s1/dev/pr/clear-browsing-data/web-ext-config.js")
[program.js][error] 
UsageError: The config file at /media/s1/dev/pr/clear-browsing-data/web-ext-config.js specified an unknown option: "0"
    at applyConfigToArgv (/media/s1/dev/pr/clear-browsing-data/node_modules/web-ext/dist/webpack:/src/config.js:57:13)
    at applyConfigToArgv (/media/s1/dev/pr/clear-browsing-data/node_modules/web-ext/dist/webpack:/src/config.js:45:17)
    at applyConfigToArgv (/media/s1/dev/pr/clear-browsing-data/node_modules/web-ext/dist/webpack:/src/config.js:45:17)
    at /media/s1/dev/pr/clear-browsing-data/node_modules/web-ext/dist/webpack:/src/program.js:195:24
    at Array.forEach (<anonymous>)
    at Program._callee$ (/media/s1/dev/pr/clear-browsing-data/node_modules/web-ext/dist/webpack:/src/program.js:193:19)
    at tryCatch (/media/s1/dev/pr/clear-browsing-data/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/media/s1/dev/pr/clear-browsing-data/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/media/s1/dev/pr/clear-browsing-data/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/media/s1/dev/pr/clear-browsing-data/node_modules/web-ext/dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:1)
    at /media/s1/dev/pr/clear-browsing-data/node_modules/web-ext/dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:1
    at <anonymous>

[program.js][debug] Command executed: run

```

### What is the expected or desired behavior?
The browser preferences should be applied without errors.

### Version information (for bug reports)

* **Firefox version**: 57.0.4
* **Your OS and version**: Arch Linux

````
$ node --version && npm --version && web-ext --version
v8.9.1
5.5.1
2.3.1

````

**Comment by kumar303** [comment]
web-ext 2.3.2 should be available shortly with all of your reported config bugs. Thanks for helping us tighten up config file support. https://github.com/mozilla/web-ext/releases/tag/2.3.2

**Comment by dessant** [comment]
Thanks for the quick release! 😋
