### ISSUE TITLE
web-ext run broken with Firefox Nightly 60.0a1 (2018-03-07)

### ISSUE THREAD

**Issue by eeejay** [mozilla/web-ext#1282]
### Is this a feature request or a bug?
Bug

### What is the current behavior?
I get the following stack:
```
WebExtError: Remote Firefox: listTabs() error: unknownError: error occurred while processing 'listTabs: TypeError: this.mPanelContainer is null
Stack: TabBrowser@chrome://browser/content/tabbrowser.js:25:5
@chrome://browser/content/browser.js:148:46
get@resource://gre/modules/XPCOMUtils.jsm:194:21
BrowserTabList.prototype._getSelectedBrowser@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/webbrowser.js:223:3
BrowserTabList.prototype.getList@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/webbrowser.js:264:23
onListTabs@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/root.js:309:27
Async*onPacket@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1762:15
_onJSONObjectReady/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/transport/transport.js:482:11
exports.makeInfallible/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14
exports.makeInfallible/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14
Line: 25, column: 5
    at /opt/node/lib/node_modules/web-ext/dist/webpack:/src/firefox/remote.js:97:25
    at /opt/node/lib/node_modules/web-ext/node_modules/firefox-client/lib/client-methods.js:73:9
    at Client.handleMessage (/opt/node/lib/node_modules/web-ext/node_modules/firefox-client/lib/client.js:161:7)
    at Client.readMessage (/opt/node/lib/node_modules/web-ext/node_modules/firefox-client/lib/client.js:220:10)
    at Client.onData (/opt/node/lib/node_modules/web-ext/node_modules/firefox-client/lib/client.js:186:16)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:250:12)
    at readableAddChunk (_stream_readable.js:237:11)
    at Socket.Readable.push (_stream_readable.js:195:10)
    at TCP.onread (net.js:586:20)
```

### What is the expected or desired behavior?

Firefox should open with the extension

### Version information (for bug reports)

* **Firefox version**: 60.0a1 (2018-03-07)
* **Your OS and version**: Fedora 27
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
v8.0.0
5.7.1
2.4.0

**Comment by kumar303** [comment]
Huh. I see a different error on macOS Nightly (same version) but it's also broken.

```
[firefox/index.js][debug] Firefox stderr: JavaScript strict warning: resource://devtools/shared/base-loader.js -> resource://devtools/shared/security/socket.js, line 779: ReferenceError: reference to undefined property "_handshakeTimeout"
[firefox/index.js][debug] Firefox stderr: JavaScript strict warning: resource:///modules/CustomizableUI.jsm, line 2463: ReferenceError: reference to undefined property "disabled"
[firefox/index.js][debug] Firefox stderr: JavaScript strict warning: chrome://browser/content/tabbrowser.xml, line 167: ReferenceError: reference to undefined property "gBrowser"
[firefox/index.js][debug] Firefox stderr: JavaScript error: chrome://browser/content/tabbrowser.xml, line 139: TypeError: this.tabbrowser is undefined
[firefox/index.js][debug] Firefox stderr: JavaScript error: chrome://browser/content/tabbrowser.xml, line 1556: TypeError: this.parentNode.tabbrowser is undefined
[firefox/index.js][debug] Firefox stderr: JavaScript error: chrome://browser/content/tabbrowser.xml, line 287: TypeError: this.tabbrowser is undefined
[firefox/index.js][debug] Firefox stderr: JavaScript strict warning: chrome://browser/content/tabbrowser.js, line 4358: ReferenceError: reference to undefined property "initialPageLoadedFromURLBar"
[firefox/remote.js][debug] listTabs returned a falsey addonsActor: undefined
```

`web-ext run --pre-install` might be a workaround until we can get an upstream fix.

<details>
<summary>verbose log</summary>

```
$ web-ext --verbose run
[program.js][info] Version: master-33c0aeeeeabcf8e68a71f35cf96fb6e73d80b8f6
[program.js][debug] Discovering config files. Set --no-config-discovery to disable
[config.js][debug] Discovered config "/Users/kumar/.web-ext-config.js" does not exist or is not readable
[program.js][info] Applying config file: ./web-ext-config.js
[config.js][debug] Loading JS config file: "/Users/kumar/dev/sound-control/web-ext-config.js" (resolved to "/Users/kumar/dev/sound-control/web-ext-config.js")
[config.js][debug] Calling coerce() on configured value for sourceDir
[cmd/run.js][info] Running web extension from /Users/kumar/dev/sound-control/extension
[util/manifest.js][debug] Validating manifest at /Users/kumar/dev/sound-control/extension/manifest.json
[extension-runners/firefox-desktop.js][debug] Creating new Firefox profile
[firefox/index.js][debug] Running Firefox with profile at /var/folders/8g/npvxp6j96sn_07b1f6b3h0qm0000gn/T/164465f6-8222-46de-9526-f7a7022ae9ae
[firefox/index.js][debug] Checking if remote Firefox port 6005 is available
[firefox/remote.js][debug] Connecting to Firefox on port 6005
[firefox/index.js][debug] Executing Firefox binary: /Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin
[firefox/index.js][debug] Firefox args: -start-debugger-server 6005 -foreground -no-remote -profile /var/folders/8g/npvxp6j96sn_07b1f6b3h0qm0000gn/T/164465f6-8222-46de-9526-f7a7022ae9ae --url mozilla.org --url soundcloud.com --url mixcloud.com
[firefox/index.js][info] Use --verbose or open Tools > Web Developer > Browser Console to see logging
[firefox/remote.js][debug] Connecting to the remote Firefox debugger
[firefox/remote.js][debug] Connecting to Firefox on port 6005
[firefox/remote.js][debug] Retrying Firefox (0); connection error: Error: connect ECONNREFUSED 127.0.0.1:6005
[firefox/remote.js][debug] Connecting to Firefox on port 6005
[firefox/remote.js][debug] Retrying Firefox (1); connection error: Error: connect ECONNREFUSED 127.0.0.1:6005
[firefox/remote.js][debug] Connecting to Firefox on port 6005
[firefox/index.js][debug] Firefox stderr: JavaScript strict warning: resource://gre/modules/addons/XPIProvider.jsm, line 5053: ReferenceError: reference to undefined property "applySoftBlock"
[firefox/remote.js][debug] Retrying Firefox (2); connection error: Error: connect ECONNREFUSED 127.0.0.1:6005
[firefox/remote.js][debug] Connecting to Firefox on port 6005
[firefox/index.js][debug] Firefox stderr: JavaScript strict warning: resource://gre/modules/addons/XPIProvider.jsm, line 4378: ReferenceError: reference to undefined property "_installLocation"
[firefox/index.js][debug] Firefox stderr: Unable to read VR Path Registry from /Users/kumar/Library/Application Support/OpenVR/.openvr/openvrpaths.vrpath
[firefox/remote.js][debug] Retrying Firefox (3); connection error: Error: connect ECONNREFUSED 127.0.0.1:6005
[firefox/remote.js][debug] Connecting to Firefox on port 6005
[firefox/remote.js][debug] Retrying Firefox (4); connection error: Error: connect ECONNREFUSED 127.0.0.1:6005
[firefox/remote.js][debug] Connecting to Firefox on port 6005
[firefox/remote.js][debug] Retrying Firefox (5); connection error: Error: connect ECONNREFUSED 127.0.0.1:6005
[firefox/remote.js][debug] Connecting to Firefox on port 6005
[firefox/index.js][debug] Firefox stdout: Started debugger server on 6005
[firefox/remote.js][debug] Retrying Firefox (6); connection error: Error: connect ECONNREFUSED 127.0.0.1:6005
[firefox/remote.js][debug] Connecting to Firefox on port 6005
[firefox/remote.js][debug] Connected to the remote Firefox debugger on port 6005
[firefox/index.js][debug] Firefox stderr: JavaScript strict warning: resource://devtools/shared/base-loader.js -> resource://devtools/shared/security/socket.js, line 779: ReferenceError: reference to undefined property "_handshakeTimeout"
[firefox/index.js][debug] Firefox stderr: JavaScript strict warning: resource:///modules/CustomizableUI.jsm, line 2463: ReferenceError: reference to undefined property "disabled"
[firefox/index.js][debug] Firefox stderr: JavaScript strict warning: chrome://browser/content/tabbrowser.xml, line 167: ReferenceError: reference to undefined property "gBrowser"
[firefox/index.js][debug] Firefox stderr: JavaScript error: chrome://browser/content/tabbrowser.xml, line 139: TypeError: this.tabbrowser is undefined
[firefox/index.js][debug] Firefox stderr: JavaScript error: chrome://browser/content/tabbrowser.xml, line 1556: TypeError: this.parentNode.tabbrowser is undefined
[firefox/index.js][debug] Firefox stderr: JavaScript error: chrome://browser/content/tabbrowser.xml, line 287: TypeError: this.tabbrowser is undefined
[firefox/index.js][debug] Firefox stderr: JavaScript strict warning: chrome://browser/content/tabbrowser.js, line 4358: ReferenceError: reference to undefined property "initialPageLoadedFromURLBar"
[firefox/remote.js][debug] listTabs returned a falsey addonsActor: undefined
[extension-runners/firefox-desktop.js][debug] Caught: RemoteTempInstallNotSupported: This is an older version of Firefox that does not provide an add-ons actor for remote installation. Try Firefox 49 or higher.
[program.js][error]
WebExtError: Temporary add-on installation is not supported in this version of Firefox (you need Firefox 49 or higher). For older Firefox versions, use --pre-install
    at FirefoxDesktopExtensionRunner._callee6$ (/Users/kumar/dev/web-ext/dist/webpack:/src/extension-runners/firefox-desktop.js:273:19)
    at tryCatch (/Users/kumar/dev/web-ext/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/kumar/dev/web-ext/node_modules/regenerator-runtime/runtime.js:296:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/kumar/dev/web-ext/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/kumar/dev/web-ext/dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:1)
    at /Users/kumar/dev/web-ext/dist/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:1
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

</details>

**Comment by kumar303** [comment]
Thanks for the bug report! Firefox must be missing some tests for this remote actor. I filed it upstream: https://bugzilla.mozilla.org/show_bug.cgi?id=1443917

**Comment by rpl** [comment]
As described in https://bugzilla.mozilla.org/show_bug.cgi?id=1443917#c8 this is an issue that we have to fix on the firefox-client npm dependency.

We are basically received a "tabListChanged" event while we are waiting for a "listTabs" reply here:
https://github.com/mozilla/web-ext/blob/7e2bd886f7372989fa4771a739f038b1aa4df270/src/firefox/remote.js#L95-L108

 "tabListChanged" is an unsolicited event and should be listed here in the firefox-client npm dependency:

https://github.com/harthur/firefox-client/blob/a9caacdf8f138d07195402fe1b7183c7aeb964ec/lib/client.js#L13-L26

I verified locally that just adding "tabListChanged" in the above "unsolicitedEvents" object is enough to fix "web-ext run" on Nightly.

**Comment by icl7126** [comment]
Hello,
Is there some simple workaround?
I'm using web-ext 2.4.0 with Firefox Developer Edition 60.0b2 (64-bit) and seems like it's affected as well.
I'm getting error:

> Temporary add-on installation is not supported in this version of Firefox

Using `web-ext run -f "C:\Program Files\Firefox Developer Edition\firefox.exe"`
It was working on Friday...

**Comment by kumar303** [comment]
> Is there some simple workaround?

Yes, Firefox Nightly 60.0a1 (2018-03-02) is working for me.

You can save it to any path on your system and execute `run` with the path to that version of Firefox.

**Comment by milouse** [comment]
@icl7126 I can confirm @rpl fix: by editing `node_modules/firefox-client/lib/client.js` inside web-ext node module in order to add `"tabListChanged": "tabListChanged"` to the `unsolicitedEvents` variable, I'm now able again to start Firefox nightly without problem.

The PR is already submitted to the upstream package: harthur/firefox-client#16

**Comment by eeejay** [comment]
Since firefox-client is unmaintained, it may be worth forking it.

**Comment by kumar303** [comment]
I pushed [2.5.0](https://github.com/mozilla/web-ext/releases/tag/2.5.0) for this fix. The tag is building now and should show up on npm shortly.
