### ISSUE TITLE
WebExtError: installTemporaryAddon: Error: unknownError: 

### ISSUE THREAD

**Issue by codeman101** [mozilla/web-ext#1371]
### Is this a feature request or a bug?
bug

### What is the current behavior?
```
Running web extension from C:\Users\user\Documents\ImageDownloader
Use --verbose or open Tools > Web Developer > Browser Console to see logging

WebExtError: installTemporaryAddon: Error: unknownError: Could not install add-on at 'C:\Users\user\Documents\ImageDownloader': Error: Extension is invalid
    at C:\Users\user\AppData\Roaming\npm\node_modules\web-ext\dist\webpack:\src\firefox\remote.js:116:27
    at Client.handleMessage (C:\Users\user\AppData\Roaming\npm\node_modules\web-ext\dist\webpack:\node_modules\@cliqz-oss\firefox-client\lib\client.js:162:1)
    at Client.readMessage (C:\Users\user\AppData\Roaming\npm\node_modules\web-ext\dist\webpack:\node_modules\@cliqz-oss\firefox-client\lib\client.js:221:1)
    at Client.onData (C:\Users\user\AppData\Roaming\npm\node_modules\web-ext\dist\webpack:\node_modules\@cliqz-oss\firefox-client\lib\client.js:187:1)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)

[firefox-profile] cannot delete profileDir on exit C:\Users\user\AppData\Local\Temp\adad204b-6675-4f08-8b47-ab296364f6c2 { Error: EBUSY: resource busy or locked, unlink 'C:\Users\user\AppData\Local\Temp\adad204b-6675-4f08-8b47-ab296364f6c2\cert9.db'
    at Object.fs.unlinkSync (fs.js:1061:18)
    at rimrafSync (C:\Users\user\AppData\Roaming\npm\node_modules\web-ext\node_modules\fs-extra\lib\remove\rimraf.js:254:15)
    at options.readdirSync.forEach.f (C:\Users\user\AppData\Roaming\npm\node_modules\web-ext\node_modules\fs-extra\lib\remove\rimraf.js:291:39)
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\user\AppData\Roaming\npm\node_modules\web-ext\node_modules\fs-extra\lib\remove\rimraf.js:291:26)
    at rmdirSync (C:\Users\user\AppData\Roaming\npm\node_modules\web-ext\node_modules\fs-extra\lib\remove\rimraf.js:281:7)
    at Object.rimrafSync (C:\Users\user\AppData\Roaming\npm\node_modules\web-ext\node_modules\fs-extra\lib\remove\rimraf.js:252:7)
    at FirefoxProfile._cleanOnExit (C:\Users\user\AppData\Roaming\npm\node_modules\web-ext\node_modules\firefox-profile\lib\firefox_profile.js:253:10)
    at process.FirefoxProfile.onExit (C:\Users\user\AppData\Roaming\npm\node_modules\web-ext\node_modules\firefox-profile\lib\firefox_profile.js:144:12)
    at emitOne (events.js:121:20)
  errno: -4082,
  code: 'EBUSY',
  syscall: 'unlink',
  path: 'C:\\Users\\user\\AppData\\Local\\Temp\\adad204b-6675-4f08-8b47-ab296364f6c2\\cert9.db' }
```

### What is the expected or desired behavior?
for it to run successfully in firefox window.

### Version information (for bug reports)

* **Firefox version**: 62.0.2
* **Your OS and version**: Windows 10 1803
* Paste the output of these commands:

````
node --version v8.12.0
 npm --version 6.4.1
 web-ext --version 2.9.1
````
I saw part of the same issue in another issue on here but wanted to post my own since mine involves more than the part the ends at TCP.onread. Also this error doesn't occur with the example beastify extension but when I try to analyze the error message myself the only thing I can come up with is that the error looks to be an issue with the web-ext files. If I'm wrong can someone please help me fix this? I'm trying create my first ever browser extension and at this point I can't see what's wrong.

Also if you need me to share my code to help resolve the error please let me know. I haven't pushed the project to my github yet but I'd be more than happy to do so if it gets this resolved.

**Comment by rpl** [comment]
@codeman101 The error ["Error is invalid" is actually generated from Firefox when an extension's manifest is being loaded and it has errors and the installation can't be completed successfully](https://searchfox.org/mozilla-central/rev/819cd31a93fd50b7167979607371878c4d6f18e8/toolkit/mozapps/extensions/internal/XPIInstall.jsm#441), and so it should be an issue in the extension that is triggering the error and not an issue in web-ext itself. 

Firefox should provide some additional details which should be logged by web-ext run when running with the --verbose option, another option to get the underlying error is to try to install the extension temporarily from "about:debugging" (which should show a warning message with the underlying manifest error in the "about:debugging" page).

Do you mind to try to install your extension from "about:debugging" (and/or with `web-ext run --verbose`) and check that the extension manifest doesn't actually have errors?

In the meantime I'm going to close this issue as invalid, because as described above it is very likely an error in the extension manifest, nevertheless feel free to re-open the bug if the same extension is installing without any error from "about:debugging" but it fails from "web-ext run" and you can attach your extension (or a minimal test extension that trigger the issue) so that we can investigate the issue more deeply.

**Comment by Rob--W** [comment]
From Firefox 139, errors will include more details beyond "Extension is invalid": https://bugzilla.mozilla.org/show_bug.cgi?id=1960285
