### ISSUE TITLE
v4.2.0 appears to be broken for Nightly on MacOS

### ISSUE THREAD

**Issue by rehandalal** [mozilla/web-ext#1892]
### Is this a feature request or a bug?
A bug

### What is the current behavior?

**Note: I do not see this issue on Linux only MacOS**

STR:
- Run `web-ext run` pointed at nightly.
- This is the output:
  ```
  $ ./node_modules/.bin/web-ext run -s dist --firefox=Applications/Firefox2.app/Contents/MacOS/firefox-bin --verbose
  [program.js][info] Version: 4.2.0
  [program.js][debug] Discovering config files. Set --no-config-discovery to disable
  [config.js][debug] Discovered config "/Users/tiffanytran/.web-ext-config.js" does not exist or is not readable
  [program.js][info] Applying config files: ./package.json, ./web-ext-config.js
  [config.js][debug] Loading JS config file: "/Users/tiffanytran/Desktop/normandy-devtools/package.json" (resolved to "/Users/tiffanytran/Desktop/normandy-devtools/package.json")
  [config.js][debug] Looking for webExt key inside package.json file
  [config.js][debug] Config file /Users/tiffanytran/Desktop/normandy-devtools/package.json did not define any options. Did you set module.exports = {...}?
  [config.js][debug] Loading JS config file: "/Users/tiffanytran/Desktop/normandy-devtools/web-ext-config.js" (resolved to "/Users/tiffanytran/Desktop/normandy-devtools/web-ext-config.js")
  [config.js][debug] Calling coerce() on configured value for pref
  [cmd/run.js][info] Running web extension from /Users/tiffanytran/Desktop/normandy-devtools/dist
  [util/manifest.js][debug] Validating manifest at /Users/tiffanytran/Desktop/normandy-devtools/dist/manifest.json
  [extension-runners/firefox-desktop.js][debug] Creating new Firefox profile
  [firefox/index.js][info] Setting custom Firefox preferences: {
    "extensions.legacy.enabled": true,
    "extensions.experiments.enabled": true
  }
  [firefox/index.js][debug] Running Firefox with profile at /var/folders/8x/5f503wtn0_b8z232nky5ypc00000gn/T/dd93e6a1-68df-481c-8ff5-6808894c4c6d
  Error: spawn Applications/Firefox2.app/Contents/MacOS/firefox-bin ENOENT
      at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
      at onErrorNT (internal/child_process.js:456:16)
  ```

### What is the expected or desired behavior?
Nightly should run and the web extension should be installed

### Version information (for bug reports)

* **Firefox version**: 77.0a1 (2020-04-21)
* **Your OS and version**: MacOS 10.14.3
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
```
v12.9.1
6.10.3
4.2.0
```

**Comment by Rob--W** [comment]
You're pointing `web-ext` to a non-existing location. Why are you passing a custom path instead of using `web-ext run -f nightly`?

**Comment by rehandalal** [comment]
`web-ext run -f nightly` worked, thanks!
