### ISSUE TITLE
When R is pressed `web-ext run throws Error: Unexpected packet from actor root{"addons..

### ISSUE THREAD

**Issue by Rob--W** [mozilla/web-ext#1911]
### Is this a feature request or a bug?
Bug.

### What is the current behavior?

Start `web-ext run` with any extension and keep R pressed. Soon `web-ext` throws and exits, with the following log:

```
Last extension reload: 19:53:50 GMT+0200 (Central European Summer Time)
/path/to/node_modules/web-ext/node_modules/@cliqz-oss/firefox-client/lib/client.js:174
      throw new Error("Unexpected packet from actor " +  message.from
            ^
Error: Unexpected packet from actor root{"addons":[{"actor":"server1.conn0.webExtensionDescriptor7","debuggable":true, ...... "actor":"server1.conn0.webExtensionDescriptor24","id":"gmp-gmpopenh264","manifestURL":null,"name":"OpenH264 Video Codec provided by Cisco Systems, Inc.","traits":{"isDescriptor":true},"type":"plugin","warnings":[]}],"from":"root"}
    at Client.handleMessage (/path/to/node_modules/web-ext/node_modules/@cliqz-oss/firefox-client/lib/client.js:174:13)
    at Client.readMessage (/path/to/node_modules/web-ext/node_modules/@cliqz-oss/firefox-client/lib/client.js:221:10)
    at Client.onData (/path/to/node_modules/web-ext/node_modules/@cliqz-oss/firefox-client/lib/client.js:187:16)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:302:12)
    at readableAddChunk (_stream_readable.js:278:9)
    at Socket.Readable.push (_stream_readable.js:217:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

```

I can reproduce with a minimal extension, i.e. an empty directory whose `manifest.json` consists of just `{"manifest_version":2,"version":"1","name":"x"}`

### What is the expected or desired behavior?
`web-ext` should not throw / crash.

### Version information (for bug reports)

node v14.2.0
npm 6.14.4
web-ext 4.2.0
Firefox Beta 77.0b6
ArchLinux

**Comment by Yrkan** [comment]
Just tested with the latest version of web-ext and it seems to be already **fixed**.
