### ISSUE TITLE
Lots of Node warnings when using `web-ext run`

### ISSUE THREAD

**Issue by ariasuni** [mozilla/web-ext#1916]
### What is the current behavior?
Running `web-ext run` produces a lot of warnings:

<details><summary>Trace</summary>
<p>

```
(node:17026) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17026) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:17026) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
```
</p>
</details>

<details><summary>Full trace</summary>
<p>

```(node:16205) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/cat.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/cd.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/chmod.js:32:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/cp.js:6:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/dirs.js:5:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/dirs.js:8:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/dirs.js:11:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/echo.js:3:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/tempdir.js:5:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/pwd.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/exec.js:10:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/ls.js:8:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/find.js:6:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/grep.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/head.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/ln.js:5:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/mkdir.js:5:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/rm.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/mv.js:7:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/sed.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/set.js:3:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/sort.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/tail.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/test.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/to.js:5:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/toEnd.js:5:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/touch.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/uniq.js:13:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:16205) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object._register [as register] (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/home/ariasuni/projets/javascript/tabcenter-reborn/node_modules/shelljs/src/which.js:5:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
```
</p>
</details>

### What is the expected or desired behavior?
No warnings unrelated to the task at hand.

This is a problem in shelljs, fixed in v0.8.4. ([source](https://github.com/shelljs/shelljs/issues/991#issuecomment-619316520))

### Version information (for bug reports)

* **Your OS and version**: Arch Linux
* node v14.3.0
* npm 6.14.5 and yarn 1.22.4
* web-ext 4.2.0

**Comment by Rob--W** [comment]
Depends on https://github.com/kurttheviking/git-rev-sync-js/pull/52

**Comment by Rob--W** [comment]
I've put up a patch to fix this.

And side note, thanks for showing the  `<details><summary>[spoiler description]</summary> [spoiler content here]</details>` trick. It makes the bug report more readable :)

<details><summary>[spoiler description]</summary> [spoiler content here]</details>

**Comment by ariasuni** [comment]
I learned the trick about the `details` and `summary` tags a while ago, and ended up saving it as a reply because I use it so often (first icon starting on the right of the toolbar when redacting a comment). I’m happy if it’s useful to others :)
