### ISSUE TITLE
"Invalid regular expression" error after upgrading from 4.3.0 to 5.0.0

### ISSUE THREAD

**Issue by mpopp75** [mozilla/web-ext#1977]
After upgrading to 5.0.0, I get the error message:

/usr/local/lib/node_modules/web-ext/node_modules/camelcase/index.js:69
		.replace(/[_.\- ]+([\p{Alpha}\p{N}_]|$)/gu, (_, p1) => p1.toLocaleUpperCase())
  ^
SyntaxError: Invalid regular expression: /[_.\- ]+([\p{Alpha}\p{N}_]|$)/: Invalid escape
    at camelCase (/usr/local/lib/node_modules/web-ext/node_modules/camelcase/index.js:69:3)
    at A.command (/usr/local/lib/node_modules/web-ext/dist/web-ext.js:1:31702)
    at Object.F [as main] (/usr/local/lib/node_modules/web-ext/dist/web-ext.js:1:36712)
    at Object.<anonymous> (/usr/local/lib/node_modules/web-ext/bin/web-ext:7:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

### Version information

* **Firefox version**: 79.0
* **Your OS and version**: Xubuntu 18.04 LTS (64bit)

* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
$ node --version && npm --version && web-ext --version
v8.10.0
3.5.2

/usr/local/lib/node_modules/web-ext/node_modules/camelcase/index.js:69
		.replace(/[_.\- ]+([\p{Alpha}\p{N}_]|$)/gu, (_, p1) => p1.toLocaleUpperCase())
  ^
SyntaxError: Invalid regular expression: /[_.\- ]+([\p{Alpha}\p{N}_]|$)/: Invalid escape
    at camelCase (/usr/local/lib/node_modules/web-ext/node_modules/camelcase/index.js:69:3)
    at A.command (/usr/local/lib/node_modules/web-ext/dist/web-ext.js:1:31702)
    at Object.F [as main] (/usr/local/lib/node_modules/web-ext/dist/web-ext.js:1:36712)
    at Object.<anonymous> (/usr/local/lib/node_modules/web-ext/bin/web-ext:7:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

**Comment by Rob--W** [comment]
You're using Node 8.10.0, and we dropped support for Node 8.x in web-ext version 4.0.0 already. We weren't actively maintaining compatibility with Node 8.x, and apparently it doesn't work at all now.

Node.js 8.x is already end-of-life since last year (see https://github.com/nodejs/Release#end-of-life-releases), I recommend that you update Node.js to a more recent version.
