### ISSUE TITLE
Invalid regular expression: Invalid escape at web-ext/node_modules/camelcase.index

### ISSUE THREAD

**Issue by tomholub** [mozilla/web-ext#2031]
### Is this a feature request or a bug?

A bug

### What is the current behavior?

```
$ web-ext build --overwrite-dest --artifacts-dir=./release/firefox-consumer/ --source-dir=./build/firefox-consumer/

/home/luke/git/flowcrypt-browser/node_modules/web-ext/node_modules/camelcase/index.js:69
                .replace(/[_.\- ]+([\p{Alpha}\p{N}_]|$)/gu, (_, p1) => p1.toLocaleUpperCase())
  ^
SyntaxError: Invalid regular expression: /[_.\- ]+([\p{Alpha}\p{N}_]|$)/: Invalid escape
    at camelCase (/home/luke/git/flowcrypt-browser/node_modules/web-ext/node_modules/camelcase/index.js:69:3)
    at A.command (/home/luke/git/flowcrypt-browser/node_modules/web-ext/dist/web-ext.js:1:31889)
    at Object.F [as main] (/home/luke/git/flowcrypt-browser/node_modules/web-ext/dist/web-ext.js:1:36899)
    at Object.<anonymous> (/home/luke/git/flowcrypt-browser/node_modules/web-ext/bin/web-ext:7:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```

### What is the expected or desired behavior?

Build the extension

### Version information (for bug reports)

Does not work on web-ext 5.1.0 and 5.0.0 (camelcase was updated on 5.0.0). Works on 4.3.0 (running command as npm script - these are web-ext versions in the npm package).

My global web-ext version is 3.2.1. While preparing this bug report, I went ahead and installed 5.1.0 globally to make sure. Fails even when printing version.

```
$ npm i -g web-ext@5.1.0
$ web-ext --version

/home/luke/.nvm/versions/node/v8.10.0/lib/node_modules/web-ext/node_modules/camelcase/index.js:69
		.replace(/[_.\- ]+([\p{Alpha}\p{N}_]|$)/gu, (_, p1) => p1.toLocaleUpperCase())
  ^
SyntaxError: Invalid regular expression: /[_.\- ]+([\p{Alpha}\p{N}_]|$)/: Invalid escape
    at camelCase (/home/luke/.nvm/versions/node/v8.10.0/lib/node_modules/web-ext/node_modules/camelcase/index.js:69:3)
    at A.command (/home/luke/.nvm/versions/node/v8.10.0/lib/node_modules/web-ext/dist/web-ext.js:1:31889)
    at Object.F [as main] (/home/luke/.nvm/versions/node/v8.10.0/lib/node_modules/web-ext/dist/web-ext.js:1:36899)
    at Object.<anonymous> (/home/luke/.nvm/versions/node/v8.10.0/lib/node_modules/web-ext/bin/web-ext:7:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```

````
$ firefox --version
Mozilla Firefox 80.0.1

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

$ node --version && npm --version
v8.10.0
5.6.0
````

**Comment by Rob--W** [comment]
Node.js 8.x hasn't been supported since web-ext 4.0.0.

Node 8.x went end-of-life (i.e. unsupported) on December 31st, 2019. You should update to a more recent version of Node.
