### ISSUE TITLE
Test suite should delete created profiles to avoid leaked event listeners

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#211]
firefox-profile [adds two listeners to the process object](https://github.com/saadtazi/firefox-profile-js/blob/master/lib/firefox_profile.js#L144) that are then removed in the [deleteDir](https://github.com/saadtazi/firefox-profile-js/blob/master/lib/firefox_profile.js#L229) method.

Because the web-ext test suite does this repeatedly, you'll see output like this in the test suite log when the listeners pile up:
````
(node) warning: possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.addListener (events.js:239:17)
    at /Users/kumar/dev/web-ext/node_modules/firefox-profile/lib/firefox_profile.js:144:13
    at Array.forEach (native)
    at new FirefoxProfile (/Users/kumar/dev/web-ext/node_modules/firefox-profile/lib/firefox_profile.js:143:22)
    at /Users/kumar/dev/web-ext/dist/webpack:/tests/test-firefox/test.firefox.js:262:23
    at /Users/kumar/dev/web-ext/dist/webpack:/src/util/temp-dir.js:29:14
    at run (/Users/kumar/dev/web-ext/node_modules/core-js/modules/es6.promise.js:89:22)
    at /Users/kumar/dev/web-ext/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/Users/kumar/dev/web-ext/node_modules/core-js/modules/_microtask.js:14:5)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
````

I think we can fix this by calling `deleteDir()` explicitly somehow.

**Comment by kumar303** [comment]
@shubheksha I looked at this bug in detail and I think it will be really hard to fix. The more I thought about it, I don't think adding listeners to the `process` `exit` event is going to slow down the suite in any noticeable way. I'm not sure it's worth spending too much time on this bug.
