### ISSUE TITLE
ERR_INVALID_ARG_TYPE error when using multiple --watch-file cli options 

### ISSUE THREAD

**Issue by rpl** [mozilla/web-ext#2122]
### Is this a feature request or a bug?

bug

### What is the current behavior?

Execute `web-ext` run with multiple --watch-file options:
```web-ext run --watch-file public/build/build.js --watch-file public/addon-build/background.js --watch-file public/addon-build/content.js``` 

The following error is logged:
```
[program.js][error]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array
    at new NodeError (node:internal/errors:278:15)
    at validateString (node:internal/validators:123:11)
    at Object.dirname (node:path:1172:5)
    at WatcherManager.watchFile (/.../node_modules/watchpack/lib/watcherManager.js:27:23)
    at Watchpack.<anonymous> (/.../node_modules/watchpack/lib/watchpack.js:38:49)
    at Array.map (<anonymous>)
    at Watchpack.watch (/home/dexter/rally-core-addon/node_modules/watchpack/lib/watchpack.js:37:28)
    at u (/home/dexter/rally-core-addon/node_modules/web-ext/dist/web-ext.js:1:25310)
    at g (/home/dexter/rally-core-addon/node_modules/web-ext/dist/web-ext.js:1:13097)
    at m (/home/dexter/rally-core-addon/node_modules/web-ext/dist/web-ext.js:1:13437)
6:33
```

The issue is likely triggered because passing `--watch-file` multiple times does make it an array instead of a string.

### What is the expected or desired behavior?

- options 1: a more clear error that tells the user that --watch-file can only be passed ones 
- options 2: support multiple --watch-file options

**Comment by rpl** [comment]
Closing as a duplicate of #2104 (which was already filed for the same issue).
