### ISSUE TITLE
Wrong activity being started for Fenix

### ISSUE THREAD

**Issue by palant** [mozilla/web-ext#2206]
### Is this a feature request or a bug?

Bug

### What is the current behavior?

The following command fails:

    web-ext run --target=firefox-android --android-device=id

Error message:

> Error: Activity class {org.mozilla.fenix.debug/org.mozilla.fenix.App} does not exist.

This works correctly with an explicit `--firefox-apk-component '.HomeActivity'` parameter.

### What is the expected or desired behavior?

This should launch Fenix using the correct activity class.

### Version information (for bug reports)

* **Firefox version**: 88.0 (built from source)
* **Your OS and version**: Android 11
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
> v15.11.0
> 7.6.0
> 6.0.0

**Comment by palant** [comment]
Actually, an explicit `--firefox-apk-component org.mozilla.fenix.debug.App` works as well. This only fails when Fenix is compiled from source, not with the official Nightly.

**Comment by Rob--W** [comment]
@jonalmeida The current logic for determining the "APK component" (activity identifier) is based on the discussion starting from your comment at https://github.com/mozilla/web-ext/pull/1871#issuecomment-605400070 :

> What it's sending: `org.mozilla.reference.browser.debug/org.mozilla.reference.browser.debug.BrowserActivity`
> What it should be sending: `org.mozilla.reference.browser.debug/org.mozilla.reference.browser.BrowserActivity`

The logic was implemented at https://github.com/mozilla/web-ext/pull/1941

In this bug report, it is apparent that `org.mozilla.fenix.debug.App` should be used instead of `org.mozilla.fenix.App`, which is in contradiction with the previously described logic.

I guess that we can avoid prepending a fixed package identifier when `.App` is used, i.e. changing the condition from `if (apkComponent.startsWith('.')) {` to `if (apkComponent !== ".App" && apkComponent.startsWith('.')) {` at https://github.com/mozilla/web-ext/blame/ac207c6fdca5c806949adcaa7c54105ce278f606/src/util/adb.js#L328 

@jonalmeida What do you suggest to resolve this bug? Does my suggestion make sense?

**Comment by jonalmeida** [comment]
Maybe there is some inconsistency within the two mobile apps, there were some variant changes that could have affected this?

**Comment by Juraj-Masiar** [comment]
Just to confirm, **using `web-ext` with Nightly on Android is currently not possible**, correct?

I have these 3 commands for Nightly / Beta / Release:
```cmd
web-ext run --target=firefox-android --android-device=emulator-5554 --firefox-apk=org.mozilla.fenix --adb-remove-old-artifacts
web-ext run --target=firefox-android --android-device=emulator-5554 --firefox-apk=org.mozilla.firefox_beta --adb-remove-old-artifacts
web-ext run --target=firefox-android --android-device=emulator-5554 --firefox-apk=org.mozilla.firefox --adb-remove-old-artifacts
```
And only Nightly doesn't start
```
Error: Activity class {org.mozilla.fenix/org.mozilla.fenix.App} does not exist.
    at C:\Users\juraj\AppData\Roaming\npm\node_modules\web-ext\node_modules\@devicefarmer\adbkit\dist\src\adb\command\host-transport\startactivity.js:44:31
    at tryCatcher (C:\Users\juraj\AppData\Roaming\npm\node_modules\web-ext\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\juraj\AppData\Roaming\npm\node_modules\web-ext\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\juraj\AppData\Roaming\npm\node_modules\web-ext\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\juraj\AppData\Roaming\npm\node_modules\web-ext\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\juraj\AppData\Roaming\npm\node_modules\web-ext\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\juraj\AppData\Roaming\npm\node_modules\web-ext\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\juraj\AppData\Roaming\npm\node_modules\web-ext\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\juraj\AppData\Roaming\npm\node_modules\web-ext\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Users\juraj\AppData\Roaming\npm\node_modules\web-ext\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:491:21)
```

**Comment by TitoGrine** [comment]
I don't believe this explains the bug detailed in this issue, but I found a similar problem.

You can change the app icon of Firefox Android by going to `Settings` -> `Customize` -> `App icon`, and selecting a different one. If the icon is not `Default`  running `web-ext run --target=firefox-android ...` throws a similar error:

> Error: Activity class {org.mozilla.firefox/org.mozilla.firefox.App} does not exist.

Didn't want to create a duplicate issue, but let me know if this warrants creating a new issue.

**Comment by jonalmeida** [comment]
> Didn't want to create a duplicate issue, but let me know if this warrants creating a new issue.

@TitoGrine this sounds like a Firefox Android bug with the new app icon is creating a new alias that web-ext can no longer find. Can you file a bug here: https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox%20for%20Android&component=Settings

**Comment by TitoGrine** [comment]
@jonalmeida Of course, I've filed [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=2008078).
