### ISSUE TITLE
Unable to sign extensions

### ISSUE THREAD

**Issue by shirshak55** [mozilla/web-ext#2228]
### Is this a feature request or a bug?
Bug 

### What is the expected or desired behavior?
It should have signed extension w/o any issue

### Version information (for bug reports)

* **Firefox version**: 87
* **Your OS and version**: Windows
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````

```
v15.11.0
7.6.0
6.1.0
```

When I try to sign extensions it shows me signing error.
```
$ web-ext sign --api-key=user:111:111--api-secret=12343212--api-url-prefix=https://addons-dev.allizom.org/api/v5
Building web extension from C:\Users\quantum\Desktop\projects\Moz\BrandedExt
No extension ID specified (it will be auto-generated)

Error: Received bad response from the server while requesting https://addons-dev.allizom.org/api/v5/addons/

status: 401
response: {"detail":"Unknown JWT iss (issuer)."}
headers: {"allow":"GET, POST, PUT, HEAD, OPTIONS","content-security-policy":"script-src https://www.google-analytics.com/analytics.js https://www.google.com/recaptcha/ h
ttps://www.recaptcha.net/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.gstatic.cn/recaptcha/ https://addons.cdn.mozilla.net https://addons-dev-cdn.allizom.or
g; form-action 'self'; base-uri 'self' https://addons.mozilla.org https://addons-dev.allizom.org; font-src 'self' https://addons.cdn.mozilla.net https://addons-dev-cdn.a
llizom.org; frame-src 'self' https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/; img-src 'self' data: blob: https://addons.cdn.mozilla.net https://st
atic.addons.mozilla.net https://sentry.prod.mozaws.net https://addons-dev-cdn.allizom.org; style-src 'self' 'unsafe-inline' https://addons.cdn.mozilla.net https://addons
-dev-cdn.allizom.org; default-src 'self'; object-src 'none'; media-src https://videos.cdn.mozilla.net; connect-src 'self' https://sentry.prod.mozaws.net https://www.goog
le-analytics.com https://addons.cdn.mozilla.net https://addons-dev-cdn.allizom.org; child-src 'self' https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptch
a/; report-uri /__cspreport__","content-type":"application/json","date":"Wed, 21 Apr 2021 02:23:43 GMT","server":"nginx","set-cookie":["multidb_pin_writes=y; expires=Wed
, 21 Apr 2021 02:23:58 GMT; Max-Age=15; Path=/"],"strict-transport-security":"max-age=31536000","vary":"Origin, X-Country-Code, Accept-Language","www-authenticate":"JWT
realm=\"Access to addons.mozilla.org external API\"","x-amo-request-id":"44cfb1ca67244d4ba0d7e08a3ab5ec99","x-content-type-options":"nosniff","x-frame-options":"DENY","x
-xss-protection":"1; mode=block","content-length":"38","connection":"Close"}

    at C:\Users\quantum\AppData\Local\Yarn\Data\global\node_modules\sign-addon\dist\webpack:\sign-addon\src\amo-client.js:274:19
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at C:\Users\quantum\AppData\Local\Yarn\Data\global\node_modules\web-ext\dist\web-ext.js:1:11436
    at O.execute (C:\Users\quantum\AppData\Local\Yarn\Data\global\node_modules\web-ext\dist\web-ext.js:1:64444)


```

If I use production prefix it gives me following error:

```
No extension ID specified (it will be auto-generated)

Error: Received bad response from the server while requesting https://addons.mozilla.org/api/v5/addons/

status: 401
response: {"detail":"Signature has expired."}
headers: {"allow":"GET, POST, PUT, HEAD, OPTIONS","content-security-policy":"style-src 'self' 'unsafe-inline' https://addons.cdn.mozilla.net; frame-src 'self' https://ww
w.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/; connect-src 'self' https://sentry.prod.mozaws.net https://www.google-analytics.com https://addons.cdn.mozil
la.net; media-src https://videos.cdn.mozilla.net; script-src https://www.google-analytics.com/analytics.js https://www.google.com/recaptcha/ https://www.recaptcha.net/re
captcha/ https://www.gstatic.com/recaptcha/ https://www.gstatic.cn/recaptcha/ https://addons.cdn.mozilla.net; default-src 'self'; base-uri 'self' https://addons.mozilla.
org; form-action 'self'; object-src 'none'; font-src 'self' https://addons.cdn.mozilla.net; child-src 'self' https://www.google.com/recaptcha/ https://www.recaptcha.net/
recaptcha/; img-src 'self' data: blob: https://addons.cdn.mozilla.net https://static.addons.mozilla.net https://sentry.prod.mozaws.net; report-uri /__cspreport__","conte
nt-type":"application/json","date":"Wed, 21 Apr 2021 02:23:22 GMT","server":"nginx","set-cookie":["multidb_pin_writes=y; expires=Wed, 21 Apr 2021 02:23:37 GMT; Max-Age=1
5; Path=/"],"strict-transport-security":"max-age=31536000","vary":"Origin, X-Country-Code, Accept-Language","www-authenticate":"JWT realm=\"Access to addons.mozilla.org
external API\"","x-amo-request-id":"e1a864152f6945fc840ee2ae8531dd07","x-content-type-options":"nosniff","x-frame-options":"DENY","x-xss-protection":"1; mode=block","con
tent-length":"35","connection":"Close"}

    at C:\Users\quantum\AppData\Local\Yarn\Data\global\node_modules\sign-addon\dist\webpack:\sign-addon\src\amo-client.js:274:19
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at C:\Users\quantum\AppData\Local\Yarn\Data\global\node_modules\web-ext\dist\web-ext.js:1:11436
    at O.execute (C:\Users\quantum\AppData\Local\Yarn\Data\global\node_modules\web-ext\dist\web-ext.js:1:64444)

```

Its like I am unable to build ext? I don't know whose issue is this.

**Comment by rpl** [comment]
@willdurand @diox any idea what may be triggering the `401 "Signature has expired."` response (and/or the "Unknown JWT iss (issuer)."` one from -dev) on an addon submittion?

**Comment by wagnerand** [comment]
@shirshak55 Can you check your system clock is accurate?

**Comment by shirshak55** [comment]
@wagnerand 

Hmm nice catch. Would be lot better if they had mentioned it. After allowing windows to auto update now there is another issue

```
$ web-ext sign REDACTED
Building web extension from REDACTED

Error: Received bad response from the server while requesting https://addons.mozilla.org/api/v5/addons/shirshak55%40pm.me/versions
/1.9/

status: 401
response: {"detail":"JWT iat (issued at time) is invalid. Make sure your system clock is synchronized with something like TLSdate.
"}
headers: {"allow":"GET, POST, PUT, HEAD, OPTIONS","content-security-policy":"base-uri 'self' https://addons.mozilla.org; default-s
rc 'self'; connect-src 'self' https://sentry.prod.mozaws.net https://www.google-analytics.com https://addons.cdn.mozilla.net; styl
e-src 'self' 'unsafe-inline' https://addons.cdn.mozilla.net; form-action 'self'; media-src https://videos.cdn.mozilla.net; img-src
 'self' data: blob: https://addons.cdn.mozilla.net https://static.addons.mozilla.net https://sentry.prod.mozaws.net; font-src 'sel
f' https://addons.cdn.mozilla.net; frame-src 'self' https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/; script
-src https://www.google-analytics.com/analytics.js https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/ https://
www.gstatic.com/recaptcha/ https://www.gstatic.cn/recaptcha/ https://addons.cdn.mozilla.net; child-src 'self' https://www.google.c
om/recaptcha/ https://www.recaptcha.net/recaptcha/; object-src 'none'; report-uri /__cspreport__","content-type":"application/json
","date":"Wed, 21 Apr 2021 15:37:08 GMT","server":"nginx","set-cookie":["multidb_pin_writes=y; expires=Wed, 21 Apr 2021 15:37:23 G
MT; Max-Age=15; Path=/"],"strict-transport-security":"max-age=31536000","vary":"Origin, X-Country-Code, Accept-Language","www-auth
enticate":"JWT realm=\"Access to addons.mozilla.org external API\"","x-amo-request-id":"84352f0e31d84aa29011b7b8e481eaac","x-conte
nt-type-options":"nosniff","x-frame-options":"DENY","x-xss-protection":"1; mode=block","content-length":"122","connection":"Close"
}

    at C:\Users\quantum\AppData\Local\Yarn\Data\global\node_modules\sign-addon\dist\webpack:\sign-addon\src\amo-client.js:274:19
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at C:\Users\quantum\AppData\Local\Yarn\Data\global\node_modules\web-ext\dist\web-ext.js:1:11436
    at O.execute (C:\Users\quantum\AppData\Local\Yarn\Data\global\node_modules\web-ext\dist\web-ext.js:1:64444)

```

But I'm sure time is correct which is 9:24 PM (+5:45) so it should match  `Wed, 21 Apr 2021 15:37:08 GMT`. I revoked and regenerated the token but this error is not going.

**Comment by wagnerand** [comment]
@shirshak55 I can see this error in our logs as well. I looked at the code and we throw this error only if the timestamp in the JWT token (which is in the request) is set to the future.

Would you mind double-checking that the clock is synced, for example using https://time.is/ ?

**Comment by shirshak55** [comment]
I decreased the time by 5 minutes and it worked :(. Looks like windows sync servers are broken somehow.

**Comment by wagnerand** [comment]
Great it worked out for you. Our code allows an offset of 5 seconds for that timestamp, but if your clock is off for more than 5 seconds in either direction, then submission fails with that error.

**Comment by Voltra** [comment]
For those who like me get this issue (for instance on Windows 11). Go to your time settings, hit the sync now button and try again. It just works
