### ISSUE TITLE
Can not grant android.permission.WRITE_EXTERNAL_STORAGE to org.mozilla.fenix

### ISSUE THREAD

**Issue by TheGameratorT** [mozilla/web-ext#2304]
### Is this a feature request or a bug?
Bug

### What is the current behavior?
Can't test my extensions on Firefox for Android because it's package doesn't ask for android.permission.WRITE_EXTERNAL_STORAGE.
```
D:\MyUser\Dev\Vs\PrivateCookies>web-ext run -t firefox-android --adb-device ifjbnnvsmv7hbqwg --firefox-apk org.mozilla.fenix
Running web extension from D:\MyUser\Dev\Vs\PrivateCookies
Selected ADB device: ifjbnnvsmv7hbqwg

s: Required android.permission.WRITE_EXTERNAL_STORAGE has not be granted for org.mozilla.fenix. Please grant them using the Android Settings or using the following adb command:
         adb shell pm grant org.mozilla.fenix android.permission.WRITE_EXTERNAL_STORAGE



D:\MyUser\Dev\Vs\PrivateCookies>adb shell pm grant org.mozilla.fenix android.permission.WRITE_EXTERNAL_STORAGE

Exception occurred while executing 'grant':
java.lang.SecurityException: Package org.mozilla.fenix has not requested permission android.permission.WRITE_EXTERNAL_STORAGE
        at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:446)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermissionInternal(PermissionManagerService.java:1491)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1444)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2300)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:251)
        at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
        at android.os.ShellCommand.exec(ShellCommand.java:44)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22202)
        at android.os.Binder.shellCommand(Binder.java:929)
        at android.os.Binder.onTransact(Binder.java:813)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4687)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4449)
        at android.os.Binder.execTransactInternal(Binder.java:1159)
        at android.os.Binder.execTransact(Binder.java:1123)
```

### What is the expected or desired behavior?
The extension should be temporarily loaded in Firefox for Android.

### Version information (for bug reports)

* **Firefox version**: Nightly 93.0a1
* **OS and version**: Android 11 RP1A.200720.011 (MIUI 12.5.2.0 RGGEUXM)

````
node version: v14.17.0
npm version: 6.14.13
web-ext version: 6.3.0
````

**Comment by m-khvoinitsky** [comment]
Same here.
* Firefox Nightly 93.0a1
* Galaxy Tab S7+ with Android 11

**Comment by jduelfer** [comment]
I opened [the above issue in the Fenix repo](https://github.com/mozilla-mobile/fenix/issues/21018). Experiencing the same on Galaxy A72 with Android 11.

**Comment by jduelfer** [comment]
[Installation from source](https://addons.mozilla.org/en-US/firefox/addon/github-extension-installer/) working great until this gets pushed to a new npm version. Thanks for tackling this! Got my add-on running nicely on my Galaxy A72 with Android 11.
