### ISSUE TITLE
Extension not signing (internal/modules/cjs/loader.js:818  Error: Cannot find module '../dist/web-ext')

### ISSUE THREAD

**Issue by cr-nz** [mozilla/web-ext#2378]
### Is this a feature request or a bug?
Bug

### What is the current behavior?
I ran `./bin/web-ext sign --api-key="user:123456:123" --api-secret="abcdef0123456789"` (using the real user and password which used to work) and got the following message:

```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '../dist/web-ext'
Require stack:
- /home/crnz/Documents/deployment/web-ext/bin/web-ext
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/crnz/projects/deployment/web-ext/bin/web-ext:3:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/crnz/Documents/deployment/web-ext/bin/web-ext' ]
}

I have run the `npm install --save-dev web-ext` command as per the instructions.
```

### What is the expected or desired behavior?
Get a signed extension created.

### Version information (for bug reports)
6.7.0

* **Firefox version**:
91.5.0esr (64-bit)

* **Your OS and version**:
Debian 11

* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
v12.22.5
7.5.2
6.7.0

**Comment by Rob--W** [comment]
`bin/web-ext` doesn't necessarily look like a published web-ext version, because the stack trace references a custom directory rather than something in `node_modules`.

Can you try to use `web-ext` instead of `bin/web-ext`?

**Comment by cr-nz** [comment]
Thank you I think that started working, got a different error now:

```
Error: Received bad response from the server while requesting https://addons.mozilla.org/api/v4/addons/firefox%40mega.co.nz/versions/5.0.1b/

status: 401
response: {"detail":"Unknown JWT iss (issuer)."}
headers: {"content-type":"application/json","content-length":"38","connection":"close","allow":"GET, POST, PUT, HEAD, OPTIONS","cache-control":"s-maxage=0","content-security-policy":"font-src 'self' https://addons.mozilla.org/static-server/; object-src 'none'; img-src 'self' blob: data: https://addons.mozilla.org/static-server/ https://addons.mozilla.org/user-media/ https://sentry.prod.mozaws.net; default-src 'none'; connect-src 'self' https://sentry.prod.mozaws.net https://www.google-analytics.com; media-src https://videos.cdn.mozilla.net; form-action 'self'; style-src 'unsafe-inline' https://addons.mozilla.org/static-server/; child-src https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/; frame-src https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/; script-src https://www.google-analytics.com/analytics.js https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.gstatic.cn/recaptcha/ https://addons.mozilla.org/static-server/; report-uri /__cspreport__","date":"Thu, 10 Feb 2022 12:55:01 GMT","referrer-policy":"same-origin","server":"nginx","set-cookie":["multidb_pin_writes=y; expires=Thu, 10 Feb 2022 12:55:16 GMT; Max-Age=15; Path=/; SameSite=Lax"],"strict-transport-security":"max-age=31536000","vary":"Origin, X-Country-Code, Accept-Language","www-authenticate":"JWT realm=\"Access to addons.mozilla.org external API\"","x-amo-request-id":"4c0c212e609b493c97f008f5d3e1eea3","x-content-type-options":"nosniff","x-frame-options":"DENY","x-xss-protection":"1; mode=block","x-cache":"Error from cloudfront","via":"1.1 90b76e653c2ec3d955102c951a3c0250.cloudfront.net (CloudFront)","x-amz-cf-pop":"GRU1-C1","x-amz-cf-id":"9IuyyTW5Cn_gZ4T58bUpl4EA3CieSzt9DByoSxRe74c5RYvqDaLt8w=="}

    at /usr/local/lib/node_modules/web-ext/node_modules/sign-addon/dist/webpack:/sign-addon/src/amo-client.js:278:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at /usr/local/lib/node_modules/web-ext/dist/web-ext.js:1:11436
    at R.execute (/usr/local/lib/node_modules/web-ext/dist/web-ext.js:1:64532)
```

I will try log into the Addons Mozilla and check the API credentials are correct.

**Comment by cr-nz** [comment]
Ok I have managed to fix the credentials issue and another issue with the accepting of terms, however I think the signing process is hanging:

```
Building web extension from /home/cr-nz/projects/deployment/firefox-web-extension
Validating add-on [.....................................]
Validation results: https://addons.mozilla.org/en-US/developers/upload/16a51a35fe7a44e9af59a9463deb4be6
Signing add-on [........................................................................]

Error: Signing is still pending, you will receive an email once there is an update on the status of your submission. If you don’t see the email after 24 hours, please check your Spam folder.
    at Timeout._onTimeout (/usr/local/lib/node_modules/web-ext/node_modules/sign-addon/dist/webpack:/sign-addon/src/amo-client.js:323:11)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

And typically it is stuck in `Awaiting Review` in Addons Mozilla beyond this 24 hours and does not get out of that.

I will say the extension is getting quite large now (I renamed it from meganz.xpi to .zip so it would attach here).

[meganz.zip](https://github.com/mozilla/web-ext/files/8057073/meganz.zip)

**Comment by Rob--W** [comment]
I'm closing this issue since it's not an issue with `web-ext`.

If your add-on continues to not be signed, reach out to amo-admins by mail.

If I look at your add-on, the set of requested permissions is minimal, which is good. The CSP does permit remote code, which could potentially be a problem, especially since the extension has 35 MB of JavaScript code. If your add-on doesn't need it, I suggest to remove the `content_security_policy` from manifest.json.
