### ISSUE TITLE
web-ext run -f nightly broke a couple of days ago

### ISSUE THREAD

**Issue by defkev** [mozilla/web-ext#2499]
### Is this a feature request or a bug?
Bug???

### What is the current behavior?
web-ext run -f nightly -p dev throws:
```
WebExtError: installTemporaryAddon: Error: Error: undefined passed where a value is required
    at RemoteFirefox.installTemporaryAddon (file:///C:/node-v16.17.0-win-x64/node_modules/web-ext/lib/firefox/remote.js:100:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FirefoxDesktopExtensionRunner.startFirefoxInstance (file:///C:/node-v16.17.0-win-x64/node_modules/web-ext/lib/extension-runners/firefox-desktop.js:228:27)
    at async FirefoxDesktopExtensionRunner.run (file:///C:/node-v16.17.0-win-x64/node_modules/web-ext/lib/extension-runners/firefox-desktop.js:45:5)
    at async Promise.all (index 0)
    at async MultiExtensionRunner.run (file:///C:/node-v16.17.0-win-x64/node_modules/web-ext/lib/extension-runners/index.js:72:5)
    at async run (file:///C:/node-v16.17.0-win-x64/node_modules/web-ext/lib/cmd/run.js:180:3)
    at async Program.execute (file:///C:/node-v16.17.0-win-x64/node_modules/web-ext/lib/program.js:289:7)
    at async file:///C:/node-v16.17.0-win-x64/node_modules/web-ext/bin/web-ext.js:13:1
```
Used to work up until a couple of days ago so probably related to a change in nightly, dunno what value is expected where undefined is passed, couldn't find anything related on Bugzilla.

### What is the expected or desired behavior?
Nightly launching with the installed extension.

### Version information (for bug reports)

* **Firefox version**: Nightly 106.0a1 (2022-09-04) (64-bit)
* **Your OS and version**: Windows 10 21H2 Build 19044
* **node version**: v16.17.0
* **npm version**: 8.19.1
* **web-ext version**: 7.2.0

**Comment by Rob--W** [comment]
This is due to a change in the devtools protocol for Nightly - https://bugzilla.mozilla.org/show_bug.cgi?id=1787409

I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1789245 in Firefox for this.

**Comment by Rob--W** [comment]
I have resolved the regression in Firefox Nightly. Today's Nightly build should work with web-ext again.

Thanks for reporting!
