### ISSUE TITLE
Firefox Nigtly 116 starts without addon loaded

### ISSUE THREAD

**Issue by Juraj-Masiar** [mozilla/web-ext#2780]
### Is this a feature request or a bug?
BUG

### What is the current behavior?
Execute:
```
web-ext run -f nightly
```
Error:
```
web-ext run -f nightly
Applying config file: ~\.web-ext-config.js
Running web extension from C:\Users\juraj\git\addons\GroupSpeedDial\firefox_dev
Setting custom Firefox preferences: {
  "browser.toolbars.bookmarks.2h2020": false,
  "browser.ctrlTab.recentlyUsedOrder": false,
  "browser.toolbars.bookmarks.visibility": "never",
  "devtools.toolbox.selectedTool": "webconsole",
  "devtools.theme.show-auto-theme-info": false,
  "devtools.webconsole.timestampMessages": true,
  "signon.rememberSignons": true,
  "devtools.theme": "dark"
}
Use --verbose or --devtools to see logging

WebExtError: installTemporaryAddon: Error: Error: Could not install add-on at 'C:\Users\juraj\git\addons\GroupSpeedDial\firefox_dev': [Exception... "AddonManager is not initialized"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/AddonManager.sys.mjs :: installTemporaryAddon :: line 2658"  data: no]
    at RemoteFirefox.installTemporaryAddon (file:///C:/Users/juraj/AppData/Roaming/npm/node_modules/web-ext/lib/firefox/remote.js:89:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FirefoxDesktopExtensionRunner.startFirefoxInstance (file:///C:/Users/juraj/AppData/Roaming/npm/node_modules/web-ext/lib/extension-runners/firefox-desktop.js:214:27)
    at async FirefoxDesktopExtensionRunner.run (file:///C:/Users/juraj/AppData/Roaming/npm/node_modules/web-ext/lib/extension-runners/firefox-desktop.js:47:5)
    at async Promise.all (index 0)
    at async MultiExtensionRunner.run (file:///C:/Users/juraj/AppData/Roaming/npm/node_modules/web-ext/lib/extension-runners/index.js:66:5)
    at async run (file:///C:/Users/juraj/AppData/Roaming/npm/node_modules/web-ext/lib/cmd/run.js:177:3)
    at async Program.execute (file:///C:/Users/juraj/AppData/Roaming/npm/node_modules/web-ext/lib/program.js:265:7)
    at async file:///C:/Users/juraj/AppData/Roaming/npm/node_modules/web-ext/bin/web-ext.js:13:1

[firefox-profile] cannot delete profileDir on exit C:\Users\juraj\AppData\Local\Temp\firefox-profilePoYRHb/ Error: EBUSY: resource busy or locked, unlink '\\?\C:\Users\juraj\AppData\Local\Temp\firefox-profilePoYRHb\cert9.db'
    at unlinkSync (node:fs:1808:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at Object.rmSync (node:fs:1276:10)
    at FirefoxProfile._cleanOnExit (C:\Users\juraj\AppData\Roaming\npm\node_modules\web-ext\node_modules\firefox-profile\lib\firefox_profile.js:292:12)
    at FirefoxProfile.onExit (C:\Users\juraj\AppData\Roaming\npm\node_modules\web-ext\node_modules\firefox-profile\lib\firefox_profile.js:172:12) {
  errno: -4082,
  syscall: 'unlink',
  code: 'EBUSY',
  path: '\\\\?\\C:\\Users\\juraj\\AppData\\Local\\Temp\\firefox-profilePoYRHb\\cert9.db'
}
```
### What is the expected or desired behavior?
Open extension in Nightly.

### Version information (for bug reports)

- **Firefox version**: 116
- **Your OS and version**: Windows 11
- Paste the output of these commands:

```
node --version && npm --version && web-ext --version
v18.16.0
9.6.2
7.6.2
```

**Comment by Rob--W** [comment]
Thanks for the report. I've filed a Bugzilla report since it is more likely for this to be rooted in Firefox than web-ext: https://bugzilla.mozilla.org/show_bug.cgi?id=1837185

**Comment by Juraj-Masiar** [comment]
**Thank you @Rob--W for fixing this so quickly! :)**
Indeed 115 was broken too, I'm surprised nobody else noticed that! (I'm using ESR for development so I miss a lot of new bugs now)
