### ISSUE TITLE
web-ext lint doesn't catch empty or malformed directories in _locales

### ISSUE THREAD

**Issue by hachi** [mozilla/web-ext#3282]
### Is this a feature request or a bug?

Bug... ish?

### What is the current behavior?

mkdir _locales/en_AQ

web-ext lint gives no warnings or errors, but web-ext run is unable to launch firefox

```
Running web extension from /home/hachi/src/stream-notifier-picarto
Profile directory /home/hachi/.web-ext-profile already exists
More info about WebExtensions debugging:
https://extensionworkshop.com/documentation/develop/debugging/

WebExtError: installTemporaryAddon: Error: Error: Could not install add-on at '/home/hachi/src/stream-notifier-picarto': Error: Extension is invalid
    at RemoteFirefox.installTemporaryAddon (file:///home/hachi/src/stream-notifier-picarto/node_modules/web-ext/lib/firefox/remote.js:94:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FirefoxDesktopExtensionRunner.startFirefoxInstance (file:///home/hachi/src/stream-notifier-picarto/node_modules/web-ext/lib/extension-runners/firefox-desktop.js:215:27)
    at async FirefoxDesktopExtensionRunner.run (file:///home/hachi/src/stream-notifier-picarto/node_modules/web-ext/lib/extension-runners/firefox-desktop.js:48:5)
    at async Promise.all (index 0)
    at async MultiExtensionRunner.run (file:///home/hachi/src/stream-notifier-picarto/node_modules/web-ext/lib/extension-runners/index.js:67:5)
    at async run (file:///home/hachi/src/stream-notifier-picarto/node_modules/web-ext/lib/cmd/run.js:173:3)
    at async Program.execute (file:///home/hachi/src/stream-notifier-picarto/node_modules/web-ext/lib/program.js:270:7)
    at async file:///home/hachi/src/stream-notifier-picarto/node_modules/web-ext/bin/web-ext.js:13:1
```

No indication is given from firefox on why the extension is invalid... I cannot find where a person might even begin to report this bug in firefox too.

### What is the expected or desired behavior?

Some sort of lint output to tell you that an empty locale directory is invalid and will not work at all.

It's also possible that runtime reload errors need to be exposed to the user somehow, there is no output from web-ext if you create an empty locales directory, but reloading stops.

### Version information (for bug reports)

- Firefox 131.0b9
- Linux Mint something
- Node v20.17.0
- NPM 10.8.2
- web-ext 8.3.0

**Comment by hachi** [comment]
Another note, possibly should be in another ticket... there is no validation that the directory names are well formed names (the locales standards say dashes, but firefox specifically or browsers in general want underscore and disallow dashes)
