### ISSUE TITLE
web-ext --version Error: Cannot find module 'regenerator-runtime

### ISSUE THREAD

**Issue by onazaro** [mozilla/web-ext#575]
### Is this a bug or feature request?
Bug

### What is the current behavior?
Right after web-ext istallation, try:
`web-ext --version`

And get the error message:
`Error: Cannot find module 'regenerator-runtime`
`    at Function.Module._resolveFilename (module.js:325:15)`
`    at Function.Module._load (module.js:276:25)`
`    at Module.require (module.js:353:17)`
`    at require (internal/module.js:12:17)`
`    at Object.module.exports.exports.__esModule (C:\Documents and Settings\Администратор\Application Data\npm\node_modules\web-ext\dist\webpack:\external "
regenerator-runtime":1:1)`
`    at __webpack_require__ (C:\Documents and Settings\Администратор\Application Data\npm\node_modules\web-ext\dist\webpack:\webpack\bootstrap 96f6c32d219c1
eb025b0:19:1)`
`    at Object.<anonymous> (C:\Documents and Settings\Администратор\Application Data\npm\node_modules\web-ext\dist\webpack:\~\babel-runtime\regenerator\inde
x.js:1:1)`
`    at __webpack_require__ (C:\Documents and Settings\Администратор\Application Data\npm\node_modules\web-ext\dist\webpack:\webpack\bootstrap 96f6c32d219c1
eb025b0:19:1)`
`    at Object.<anonymous> (C:\Documents and Settings\Администратор\Application Data\npm\node_modules\web-ext\dist\webpack:\src\program.js:9:215)`
`    at Object.<anonymous> (C:\Documents and Settings\Администратор\Application Data\npm\node_modules\web-ext\dist\web-ext.js:148:31)`

Prior to it, have two warnings installing web-ext:
`npm WARN engine web-ext@1.5.0: wanted: {"node":">=4.0.0","npm":">=3.0.0"} (current: {"node":"4.6.0","npm":"2.15.9"})`
`npm WARN optional dep failed, continuing fsevents@1.0.14`

### What is the expected or desired behavior?
Print web-ext version.

### Version information

(Please fill this in for bug reports.)

* Output of `web-ext --version`: n/a
* Output of `node --version`: v4.6.0
* Output of `npm --version`: 2.15.9
* Firefox version: 47.0
* Your OS and version: Windows XP SP3 32

**Comment by kumar303** [comment]
Win32 is a bit old but I suppose it should work. NPM 2 has some bugs in it. You could try upgrading NPM and re-installing. You would have to do it like this:
* Follow the [instructions](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) for upgrading NPM on Windows
* Delete the `node_modules` folder in your `web-ext` source
* Re-run `npm install`

I'm not sure if it will fix it but it's worth a try. Another person was able to install `web-ext` on Windows so it should be possible.

**Comment by onazaro** [comment]
Updated npm to version 3.10.8.
Web-ext seems to be working.

**Comment by kumar303** [comment]
ok, great! Let me know if you hit any other issues.

**Comment by onazaro** [comment]
The same issue on Ubuntu 16.04 64.
For now, the "recommended for most users" Node.js v4.6.0 LTS contains npm v2.15.11, which cause the problem.

Need to get latest npm:
`npm install -g npm@latest`
 
That solves the problem.

**Comment by kumar303** [comment]
The installation docs do recommend NPM 3.0: https://github.com/mozilla/web-ext#installation-from-source

However, it should work in NPM 2. I just tried the same exact versions of Node and NPM in your bug report on Mac OS X and it's working for me. We have [tests](https://github.com/mozilla/web-ext/blob/master/.travis.yml#L4) to cover Node 4 with NPM 2 and they are passing.

**Comment by onazaro** [comment]
I'm not so deep into this technology yet.
Just starting at [Getting started](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext), and there is only link to Node.JS there.
I follow the link, take version, recommended there - and get what I get, on 2 different systems.

**Comment by BigBlueHat** [comment]
I just hit the same thing...likely because NPM 2.15.x is what comes the LTS (4.6.1) variation of Node.js.

I got around this (so far at least) by just installing `regenerator-runtime` directly via `npm i -g regenerator-runtime`.

@kumar303 Would it hurt to make `regenerator-runtime` a dependency of web-ext?

**Comment by kumar303** [comment]
@BigBlueHat are you also on Windows?

It isn't actually a web-ext dependency, it's required by one of the libraries we use:
````
$ npm ls regenerator-runtime
web-ext@1.5.0 /Users/kumar/dev/web-ext
└─┬ babel-polyfill@6.16.0
  └── regenerator-runtime@0.9.5
````
I think there is some bug in NPM 2 that prevents it from getting installed. However, I cannot reproduce it on Mac OS X and our [tests don't reproduce it on Linux](https://github.com/mozilla/web-ext/blob/master/.travis.yml#L4). 

It's probably not worth spending too much time on this because 6.3.0 became the LTS version of Node at the start of this month: https://github.com/nodejs/LTS

**Comment by kumar303** [comment]
Oh! I can reproduce it on Mac, sorry. I was confused because it only happens with `npm install web-ext`, not when you run `npm install` within a source checkout of the `web-ext` repo (strange!). Let me see if there is a quick fix.

**Comment by kumar303** [comment]
I just released this in [1.6.0](https://www.npmjs.com/package/web-ext) and from my test it appears to be fixed. Thanks again for everyone's help in pinpointing this problem.

**Comment by BigBlueHat** [comment]
Uninstalled `web-ext` and `regenerator-runtime` (globally). Reinstalled `web-ext` (1.6.0). Everyone's happy now. 😸 

Thanks @kumar303!
🎩
