### ISSUE TITLE
web-ext doesn't look for Firefox Developer Edition

### ISSUE THREAD

**Issue by BigBlueHat** [mozilla/web-ext#628]
### Is this a bug or feature request?

Feature Request

### What is the current behavior?

Currently, if you run `web-ext run` with *only* Firefox Developer Edition installed the following error is thrown:
```
Error: spawn C:\Program Files (x86)\Mozilla Firefox\firefox.exe ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### What is the expected or desired behavior?

I'd like web-ext to find the Firefox Developer Edition for me, so I don't have to `--firefox` every time I run it or ever. :wink:

### Version information

(Please fill this in for bug reports.)

* Output of `web-ext --version`: 1.6.0
* Output of `node --version`: 6.9.1
* Output of `npm --version`: 3.10.8
* Firefox version: 51.0a2 (developer edition in this case)
* Your OS and version: Windows Version 10.0.14393 Build 14393

**Comment by kumar303** [comment]
Yeah, that would be nice to choose a sane default. 

BTW, there is a shortcut for this: `web-ext run --firefox=firefoxdeveloperedition` and you can also set $FIREFOX in the environment.

**Comment by kumar303** [comment]
oops, the aliases weren't documented. I fixed that in https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference?document_saved=true#--firefox

**Comment by eight04** [comment]
I guess it doesn't work on Windows or Linux.
https://github.com/mozilla-jetpack/node-fx-runner/blob/master/lib/utils.js#L121

**Comment by kumar303** [comment]
Looks like Windows never got a developer edition alias

**Comment by gasolin** [comment]
not work with firefox dev edition on windows

**Comment by eight04** [comment]
Any progress? After update, web-ext started asking us to upgrade Firefox, which is a bit weird since I don't have 32-bit Firefox installed. It might be better to change it to `Could not find 64-bit Firefox at ${someLocation}`, 
```
You are using 32-bit version of Firefox on 64-bit versions of the Windows.
Some features may not work correctly in this version. You should upgrade Firefox
 to the latest 64-bit version now!
Error: spawn C:\Program Files (x86)\Mozilla Firefox\firefox.exe ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by kumar303** [comment]
@eight04 Hmm, that sounds like a regression caused by https://github.com/mozilla-jetpack/node-fx-runner/pull/30 -- could you file a bug [here](https://github.com/mozilla-jetpack/node-fx-runner/issues) with some details? Also, are you sue you aren't running a 32-bit version of Firefox? That's what the installer defaults to, I am told.

**Comment by eight04** [comment]
Yes. My system only has Developer Edition. It was 32-bit version, but after I saw the error message I upgraded it to 64-bit. However the error still presents and I finally noticed that the error is caused by this issue.

**Comment by eight04** [comment]
https://github.com/mozilla-jetpack/node-fx-runner/issues/31

**Comment by cmoon2000** [comment]
It works for me on 64bit 
```
web-ext run -f "C:\Program Files\Firefox Developer Edition\firefox.exe"
```

**Comment by TheAifam5** [comment]
Still not fixed? O.o

**Comment by basilevs** [comment]
web-ext 4.0.0, Windows 10

If Firefox Developer Edition 64-bit is the only Firefox installation on the host, Web-ext won't select it.

```
> reusetab-firefox@1.0.0 start:firefox C:\Users\basil\git\reusetab-firefox
> web-ext run --source-dir ./

Applying config file: .\package.json
Running web extension from C:\Users\basil\git\reusetab-firefox
You are using 32-bit version of Firefox on 64-bit versions of the Windows.
Some features may not work correctly in this version. You should upgrade Firefox to the latest 64-bit version now!
Error: spawn C:\Program Files (x86)\Mozilla Firefox\firefox.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

Workaround: add `--firefox=firefoxdeveloperedition` argument (now works on Windows!).
