### ISSUE TITLE
feat: document domains accessed by web-ext sign for enterprise proxy configuration

### ISSUE THREAD

**Issue by joergsesterhenn** [mozilla/web-ext#669]
### Is this a bug or feature request?
feature request

### What is the current behavior?

We want to automate the release and sign process for web-extensions.
For this we need to configure our enterprise proxy to allow access to all required domains. 
Our IT department is very restrictive and won't allow general access to all domains for technical accounts.

While the initial "web-ext sign" request is directed towards addons.mozilla.org it gets redirected (as documented in http://addons-server.readthedocs.io/en/latest/topics/api/signing.html#downloading-signed-files).

### What is the expected or desired behavior?

Please provide a comprehensive list of (second level) domains that can possibly be accessed through the web-ext api so that enterprises can configure their proxy accordingly.
This could be part of http://addons-server.readthedocs.io/en/latest/topics/api/index.html

For a quick fix a comment in this issue would do for us.

### Version information
web-ext  1.6.0

**Comment by kumar303** [comment]
Thanks for filing this, we should definitely document this under the [--api-proxy](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference?document_saved=true#--api-proxy) docs (or some place like that).

I tried to grab a verbose log but the file URLs [are not logged](https://github.com/mozilla/sign-addon/issues/186), d'oh.

I *think* these are the only domains but I could be wrong:
* addons.mozilla.org
* addons.cdn.mozilla.net
* static.addons.mozilla.net

**Comment by joergsesterhenn** [comment]
We are currently not using the --api-proxy option but instead configured an exception in our proxy for mozilla.org (since that is what the docs said). 

However we got a timeout from a server originating from the amazon aws cloud (can provide the IP tomorrow from work). Might this be where the signed files are downloaded from?

We would also need to know these domains...

**Comment by kumar303** [comment]
I am not aware of any AWS servers but if you let me know what the domain was that timed out I can investigate

**Comment by joergsesterhenn** [comment]
This is what my logs say: 

```
[18:32:43][Step 1/1] > web-ext sign --verbose
[18:32:43][Step 1/1] 
[18:32:45][Step 1/1] [program.js][debug] Getting the version from package.json
[18:32:45][Step 1/1] [program.js][info] Version: 1.6.0
[18:32:45][Step 1/1] [util/temp-dir.js][debug] Created temporary directory: /opt/twrti/BuildAgent/temp/buildTmp/tmp-web-ext-14176PxJ3VcKA7DDt
[18:32:45][Step 1/1] [util/artifacts.js][debug] Creating artifacts directory: /opt/twrti/BuildAgent/work/664b7ee4626f1bf9/npmtest/target/archive/web-ext-artifacts
[18:32:45][Step 1/1] [util/manifest.js][debug] Validating manifest at /opt/twrti/BuildAgent/work/664b7ee4626f1bf9/npmtest/target/archive/manifest.json
[18:32:45][Step 1/1] [cmd/build.js][info] Building web extension from /opt/twrti/BuildAgent/work/664b7ee4626f1bf9/npmtest/target/archive
[18:32:45][Step 1/1] [cmd/build.js][debug] Using manifest id=[not specified]
[18:32:45][Step 1/1] [cmd/sign.js][debug] No ID file found at: /opt/twrti/BuildAgent/work/664b7ee4626f1bf9/npmtest/target/archive/.web-extension-id
[18:32:45][Step 1/1] [cmd/build.js][debug] FileFilter: ignoring file /opt/twrti/BuildAgent/work/664b7ee4626f1bf9/npmtest/target/archive/node_modules
[18:32:45][Step 1/1] [cmd/sign.js][warn] No extension ID specified (it will be auto-generated)
[18:32:45][Step 1/1] [sign-addon] Signing add-on without an ID
[18:32:45][Step 1/1] [sign-addon] [API] POST request:
[18:32:45][Step 1/1]  { url: 'https://addons.mozilla.org/api/v3/addons/',
[18:32:45][Step 1/1]   formData: 
[18:32:45][Step 1/1]    { upload: 
[18:32:45][Step 1/1]       ReadStream {
[18:32:45][Step 1/1]         _readableState: [Object],
[18:32:45][Step 1/1]         readable: true,
[18:32:45][Step 1/1]         domain: null,
[18:32:45][Step 1/1]         _events: [Object],
[18:32:45][Step 1/1]         _eventsCount: 1,
[18:32:45][Step 1/1]         _maxListeners: undefined,
[18:32:45][Step 1/1]         path: '/opt/twrti/BuildAgent/temp/buildTmp/tmp-web-ext-14176PxJ3VcKA7DDt/npmtest-0.0.1-snapshot.zip',
[18:32:45][Step 1/1]         fd: null,
[18:32:45][Step 1/1]         flags: 'r',
[18:32:45][Step 1/1]         mode: 438,
[18:32:45][Step 1/1]         start: undefined,
[18:32:45][Step 1/1]         end: undefined,
[18:32:45][Step 1/1]         autoClose: true,
[18:32:45][Step 1/1]         pos: undefined,
[18:32:45][Step 1/1]         bytesRead: 0 },
[18:32:45][Step 1/1]      version: '0.0.1-SNAPSHOT' },
[18:32:45][Step 1/1]   timeout: 300500,
[18:32:45][Step 1/1]   headers: { Authorization: '<REDACTED>', Accept: 'application/json' } }
[18:34:52][Step 1/1] [util/temp-dir.js][debug] Removing temporary directory: /opt/twrti/BuildAgent/temp/buildTmp/tmp-web-ext-14176PxJ3VcKA7DDt
[18:34:52][Step 1/1] [program.js][error] 
[18:34:52][Step 1/1] sign: Error: connect ETIMEDOUT 52.24.88.75:443
[18:34:52][Step 1/1]     at Object.exports._errnoException (util.js:1026:11)
[18:34:52][Step 1/1]     at exports._exceptionWithHostPort (util.js:1049:20)
[18:34:52][Step 1/1]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
```

A quick whois lookup revealed that 52.24.88.75  at the time belonged to:

> ISP Amazon Technologies
> Hostname ec2-52-24-88-75.us-west-2.compute.amazonaws.com
> Organization Amazon.com
> Connection Type Corporate
> Country United States
> City Wilmington, Delaware

**Comment by kumar303** [comment]
yeah, that's an elastic IP/hostname so it could change. @jasonthomas could you help us locate which static hostname belongs to 52.24.88.75 in the context of downloading signed add-on files? @joergsesterhenn is trying to whitelist all hosts related to working with the singing API.

**Comment by joergsesterhenn** [comment]
Hi @jasonthomas, hi @kumar303, any news on this? We still would like to use this service but momentarily can't due to lack of documentation...

**Comment by kumar303** [comment]
I asked for a reply in an email. You could also figure it out by running your own proxy outside of your enterprise firewall and logging all host names while you sign a test add-on. The docs for [--api-proxy](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference?document_saved=true#--api-proxy) provide info for how to do that.

**Comment by jasonthomas** [comment]
Sorry I missed this. 

Signed add-ons file will be coming from addons.mozilla.org. The IP Address on this endpoint may change at any given time unfortunately due to the nature of AWS ELB.  AWS provides a list of all possible IP addresses http://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html.

**Comment by jasonthomas** [comment]
> yeah, that's an elastic IP/hostname so it could change. @jasonthomas could you help us locate which static hostname belongs to 52.24.88.75

This is probably the address addons.mozilla.org resolved to at the time the request was made.

**Comment by kumar303** [comment]
@jasonthomas thanks! 

@joergsesterhenn Additionally, it looks like `static.addons.mozilla.net` isn't used after all. Are you needing to whitelist IP addresses instead of hosts? Maybe I missed that part.

**Comment by joergsesterhenn** [comment]
No. Domains should be fine. If the domain was mozilla.org after all, maybe there is something wrong with our proxy config. If it was mozilla.net then that might be the problem. Maybe adding mozilla.net to our proxy exceptions will suffice. I will check this and get back to you in 2017. Thanks for your great support. Have a nice christmas holiday and a good year 2017!

**Comment by joergsesterhenn** [comment]
@jaysiee: If you get bored... request a proxy exception for mozilla.net - the same way as was done for mozilla.org TIA

**Comment by kumar303** [comment]
Happy holidays to you as well! Thanks

**Comment by joergsesterhenn** [comment]
I tried again with additional proxy exception for mozilla.net.
I still get a timeout from (54.187.207.27) ec2-54-187-207-27.us-west-2.compute.amazonaws.com.
The response (with the signed webextension) does not seem to be originating from mozilla.org or mozilla.net.

**Comment by jasonthomas** [comment]
As of this moment 54.187.207.2 is associated with addons.mozilla.org, I can get a response from that IP address:

`curl --resolve addons.mozilla.org:443:54.187.207.27 https://addons.mozilla.org/en-US/firefox/ -D- -so/dev/null`

How are you validating that it belongs to mozilla.org or mozilla.net? Is it based on DNS PTR record?

**Comment by joergsesterhenn** [comment]
Thanks for your hint. We had an issue in our proxy-config. Now everything works as expected!

**Comment by kumar303** [comment]
@jasonthomas, to recap, these are the only domains one would need to allow when signing and downloading files, right? 

* addons.mozilla.org
* addons.cdn.mozilla.net

**Comment by jasonthomas** [comment]
Correct

**Comment by kumar303** [comment]
Thanks everyone!

It's now documented:
- https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext?document_saved=true#Signing_in_a_restricted_environment
- https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference?document_saved=true#--api-proxy
