### ISSUE TITLE
Feature request: JS API for web-ext

### ISSUE THREAD

**Issue by futpib** [mozilla/web-ext#683]
JS API would make it possible to use `web-ext` in build scripts (like `gulpfile.js`) without calls to system shell.

**Comment by kumar303** [comment]
Did you try it? It should work. We will be documenting this in https://github.com/mozilla/web-ext/issues/381

Try this example and let me know if it's working for you or not: https://github.com/mozilla/web-ext/issues/381#issuecomment-234089616

**Comment by futpib** [comment]
Oh, ok, it's there. It's just that I required `web-ext` and saw only `main` function, and instantly jumped to conclusion that it's all API we've got.

Is there a way to require it the ES5 way though? I see how it could work If my gulpfile was compiled with webpack/browserify + babel, but not right out of the box.

```
$ node -e "require('web-ext/src/cmd/build')"
/home/futpib/code/policeman/node_modules/web-ext/src/cmd/build.js:2
import path from 'path';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:26:33)
```

**Comment by kumar303** [comment]
Oh crap, you're right. In ES5 there is currently no way to use web-ext programmatically. We should fix that.

The reason is because in ES5 you'll have to use the compiled source which indeed only exposes `main()`:
````
$  node -e "console.log(require('web-ext/dist/web-ext'))"
{ main: [Function: main] }
````
The ES6 sources are accessible but that's not helpful:
````
$  node -e "console.log(require('web-ext/src/cmd/build'))"
/Users/kumar/tmp/web-ext-api-test/node_modules/web-ext/src/cmd/build.js:2
import path from 'path';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at [eval]:1:13
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
````
Maybe there is still a way to access the submodules in the compiled source? I'm not sure.

Anyway, as a fix, we can probably just expose the `cmd` module as a parameter of the main module.

**Comment by kumar303** [comment]
Well, actually, this should be enough. You can do a build like this:
````
> const main = require('web-ext/dist/web-ext').main;
> main(['build'], {runOptions: {shouldExitProgram: false}})
      .catch(error => console.error('CAUGHT', error));
Usage:  [options] command

Option values can also be set by declaring an environment variable prefixed
with $WEB_EXT_. For example: $WEB_EXT_SOURCE_DIR=/path is the same as
--source-dir=/path.

To view specific help for any given command, add the command name.
Example:  --help run.


Commands:
  build  Create a web extension package from source
  sign   Sign the web extension so it can be installed in Firefox
  run    Run the web extension
  lint   Validate the web extension source

Options:
  --version            Show version number                             [boolean]
  --source-dir, -s     Web extension source directory.
              [string] [required] [default: "/Users/kumar/tmp/web-ext-api-test"]
  --artifacts-dir, -a  Directory where artifacts will be saved.
                                                   [string] [required] [default:
                          "/Users/kumar/tmp/web-ext-api-test/web-ext-artifacts"]
  --verbose, -v        Show verbose output                  [boolean] [required]
  -h, --help           Show help                                       [boolean]

Not enough non-option arguments: got 0, need at least 1
Promise {
  _c: [],
  _a: undefined,
  _s: 0,
  _d: false,
  _v: undefined,
  _h: 0,
  _n: false }
> CAUGHT Error: Not enough non-option arguments: got 0, need at least 1
    at Object.self.fail (/Users/kumar/tmp/web-ext-api-test/node_modules/yargs/lib/usage.js:53:20)
    at Object.self.nonOptionCount (/Users/kumar/tmp/web-ext-api-test/node_modules/yargs/lib/validation.js:21:15)
    at parseArgs (/Users/kumar/tmp/web-ext-api-test/node_modules/yargs/yargs.js:945:20)
    at Object.Yargs.Object.defineProperty.get [as argv] (/Users/kumar/tmp/web-ext-api-test/node_modules/yargs/yargs.js:812:16)
    at Program._callee$ (/Users/kumar/tmp/web-ext-api-test/node_modules/web-ext/dist/webpack:/src/program.js:9:7845)
    at tryCatch (/Users/kumar/tmp/web-ext-api-test/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/kumar/tmp/web-ext-api-test/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/kumar/tmp/web-ext-api-test/node_modules/regenerator-runtime/runtime.js:95:21)
    at step (/Users/kumar/tmp/web-ext-api-test/node_modules/web-ext/dist/webpack:/~/babel-runtime/helpers/asyncToGenerator.js:17:1)
    at /Users/kumar/tmp/web-ext-api-test/node_modules/web-ext/dist/webpack:/~/babel-runtime/helpers/asyncToGenerator.js:35:1

>
````

**Comment by erikvold** [comment]
@kumar303 using your example above ^

I get this error: `TypeError: Path must be a string. Received [ 'build' ]`

**Comment by erikvold** [comment]
Also I've made a gulp command called `gulp build-firefox` which is running this:

```
  const webExtBuild = require("web-ext/dist/web-ext").main;
  return webExtBuild(src,
    {
      runOptions: { shouldExitProgram: false }
    })
    .then(log)
    .catch(console.error);
```

and I get this error: `Error: Unknown argument: build-firefox`

so it appears this main function from web-ext is using the command line arguments and erroring on them.

**Comment by kumar303** [comment]
Ugh, sorry, the signature changed since my comment. We really need to get this documented.

Here is an up to date (working) example for how to call `main()` from a script : https://github.com/mozilla/web-ext/blob/master/tests/unit/test.program.js#L285

**Comment by futpib** [comment]
I'd say providing a separate JS API is a better option, so that you don't "freeze" CLI implementation by telling users they can expect that it will be stable.

**Comment by kumar303** [comment]
Yep, good idea

**Comment by kumar303** [comment]
Some basic programmatic support landed here https://github.com/mozilla/web-ext/pull/1028

The PR has docs on how to use it. Once this feature gets released, I'll add the same docs to MDN.

**Comment by kumar303** [comment]
I think this would be better to document on github. See https://github.com/mozilla/web-ext/pull/1119

**Comment by kumar303** [comment]
I also added a note in the user docs back to the github docs for programmatic usage. https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext
