### ISSUE TITLE
Show context and line numbers for JSON syntax errors

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#698]
### Is this a bug or feature request?

feature

### What is the current behavior?

If you introduce a syntax error in your `manifest.json` (or in another JSON file), you will see an informative error pointing to the problem like this:

````
$ web-ext build -s extension/
Building web extension from /Users/kumar/dev/sound-control/extension

build: InvalidManifest: Error parsing manifest.json at /Users/kumar/dev/sound-control/extension/manifest.json: JSONError: Unexpected token 'p' at 49:4 in /Users/kumar/dev/sound-control/extension/manifest.json
  "permissions": ["activeTab", "tabs"],
   ^

````

### What is the expected or desired behavior?

This is helpful but I think the display should be enhanced to show a bit more context and to show line numbers. Maybe something like this:

````
$ web-ext build -s extension/
Building web extension from /Users/kumar/dev/sound-control/extension

build: InvalidManifest: Error parsing manifest.json at /Users/kumar/dev/sound-control/extension/manifest.json: 
JSONError: Unexpected token 'p' at 49:4 in /Users/kumar/dev/sound-control/extension/manifest.json
43.        "default": "Ctrl+Shift+K"
44.      },
45.      "description": "Go to the selected audible tab"
46.    }
47.  }
48.
49.  "permissions": ["activeTab", "tabs"],
      ^
50.
51.  "manifest_version": 2
````

**Comment by aniketkudale** [comment]
Hi @kumar303, I'd like to work on this!

**Comment by kumar303** [comment]
Sure thing, thanks @aniketkudale !

**Comment by kumar303** [comment]
This is how `webpack` shows errors. I think it looks really nice:

````
ERROR in ./src/popup.js
Module build failed: SyntaxError: Unexpected token, expected , (8:17)

   6 |     super(props);
   7 |     this.state = {
>  8 |       isOn: false;
     |                  ^
   9 |       code: null,
  10 |     };
  11 |   }
````

**Comment by aniketkudale** [comment]
@kumar303 This looks cool, I'll start the investigation.

**Comment by kumar303** [comment]
Keep in mind that this kind of code is pretty hard to write and it will need a lot of tests. This would be a challenging bug to work on, even for advanced developers. I'm not saying that to discourage you but only to set a realistic expectation for the amount of effort it will take.

**Comment by aniketkudale** [comment]
Oh, one question, we are targeting only JSON errors in this issue? Right?

**Comment by kumar303** [comment]
Yes. Currently, those are the only files that web-ext might complain about.

**Comment by aniketkudale** [comment]
@kumar303 This throws InvalidManifest JSON error
```
  } catch (error) {
    throw new InvalidManifest(
      `Error parsing manifest.json at ${manifestFile}: ${error}`);
}
```
Where can I get line no/column no. from `error` i.e `49:4`

**Comment by kumar303** [comment]
I'm not sure. You'd have to look at https://github.com/sindresorhus/parse-json which is what we use. The line above the one you pasted should call it like `parseJSON(...)`. Maybe you can pass it a `reviver` callback and see what you get. The docs for this lib are not great so you'll have to read the code and experiment with it.

**Comment by aniketkudale** [comment]
Thanks @kumar303 I'll take a look at it.

**Comment by shubheksha** [comment]
I came across this a while back, thought it might be useful for this issue: https://github.com/babel/babel/issues/5064

**Comment by aniketkudale** [comment]
Thanks @shubheksha, will take a look!

**Comment by kumar303** [comment]
@fluks if you still have it, could you show the stack trace you got from `web-ext run` ?

**Comment by fluks** [comment]
$ web-ext run
Running web extension from /home/fluks/open-link-to
Use --verbose or open Tools > Web Developer > Browser Console to see logging

run: WebExtError: installTemporaryAddon: Error: unknownError: Could not install add-on at '/home/fluks/open-link-to': Error: Extension is invalid
    at /home/fluks/.npm-global/lib/node_modules/web-ext/dist/webpack:/src/firefox/remote.js:9:13549
    at EventEmitter.extend.handleMessage (/home/fluks/.npm-global/lib/node_modules/web-ext/node_modules/firefox-client/lib/client.js:161:7)
    at EventEmitter.extend.readMessage (/home/fluks/.npm-global/lib/node_modules/web-ext/node_modules/firefox-client/lib/client.js:220:10)
    at EventEmitter.extend.onData (/home/fluks/.npm-global/lib/node_modules/web-ext/node_modules/firefox-client/lib/client.js:186:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:537:20)

**Comment by kumar303** [comment]
Thanks. I see. It's hitting a Firefox error because the `run` command doesn't attempt to validate locale messages. Firefox could do a lot better than saying `Extension is invalid` !
