### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by Knight-Yoshi** [mozilla/web-ext#723]
Running any _web-ext_ command in version 1.6.0 results in the same error
_Error: Module version mismatch. Expected 48, got 46._

**Comment by kumar303** [comment]
I haven't seen that. Can you tell us what version of node you are using,
what version of npm you used, and what OS and version you are on?

**Comment by Knight-Yoshi** [comment]
Node: v6.9.1
NPM: 3.10.8

I'm on macOS Sierra (10.12.3)

```
Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/[omitted]/.node_modules/lib/node_modules/web-ext/node_modules/bunyan/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/[omitted]/.node_modules/lib/node_modules/web-ext/node_modules/bunyan/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/[omitted]/.node_modules/lib/node_modules/web-ext/node_modules/bunyan/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }

```

**Comment by Knight-Yoshi** [comment]
Neither of those options solved the issue. 
Updated npm to 4.0.5
uninstalled web-ext
re-installed it
Same mismatch

Ran npm rebuild
Same mismatch

**Comment by kumar303** [comment]
You mentioned `npm rebuild` so are you installing `web-ext` from source?

This error is quite common but it's happening in a sub-dependency of ours so there's not much we can do about it. You can try reading through all the threads for how other people have solved it: https://www.google.com/search?q=node+dtrace-provider+mac+Error%3A+Module+version+mismatch.+Expected+48%2C+got+46.&ie=utf-8&oe=utf-8

**Comment by kumar303** [comment]
Specifically, this comment explains the [root cause](https://github.com/mscdex/mmmagic/issues/66#issuecomment-153432268). Usually doing the rebuild fixes this but you may also have differing versions of node or npm on your PATH so double check that you're installing it with the right version maybe?

**Comment by rpl** [comment]
@Knight-Yoshi have you already tried to remove the `node_modules/` dir and run `npm clean cache` before running `npm install` again? 

like @kumar303 pointed out, the stacktrace attached above shows that the error is raised by an npm package that we do not use directly (`dtrace-provider`), but it is imported from one of our dependency (`bunyan`).

**Comment by rpl** [comment]
@Knight-Yoshi @kumar303 The following seems to be the related issue in the node-bunyan repo: trentm/node-bunyan#216

it can provide some additional useful insight.

**Comment by Knight-Yoshi** [comment]
Thanks guys! That was annoying to solve. Ugh.

Made sure all packages were built with Node  6.9.2, that `npm` was up to date, re-installed project packages with --no-options. Finally got it resolved. :)

**Comment by rpl** [comment]
@Knight-Yoshi :tada: I'm so glad to hear that! thanks for confirming that it worked!

`npm install --no-optional` is the step that has been able to successfully workaround the issue, am I right?

**Comment by Knight-Yoshi** [comment]
@rpl I think so. That was the last thing I tried before it finally stopped complaining.

I found it in the issue you posted above. Apparently it's an optional dependency issue not compatible with OSX / macOS.
https://github.com/trentm/node-bunyan/issues/216#issuecomment-191294858

**Comment by rpl** [comment]
@Knight-Yoshi :+1: thanks 
(it can be very helpful if other users are going to meet the same issue)
