### ISSUE TITLE
341 : Cannot find module 'source-map-support'

### ISSUE THREAD

**Issue by ManuJindal** [mozilla/web-ext#813]
can any one suggest for this error?

'/Applications/Appium.app/Contents/Resources/node/bin/node' '/Applications/Appium.app/Contents/Resources/node_modules/appium-doctor/appium-doctor.js'
module.js:341
    throw err;
    ^

Error: Cannot find module '/Applications/Appium.app/Contents/Resources/node_modules/appium-doctor/appium-doctor.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

### Version information (for bug reports)
npm - 4.3.0
Appium : 1.5.3
node: 7.5.0

**Comment by shubheksha** [comment]
Hey, this look an issue which should be filed here: https://github.com/appium/appium/issues
Could you cross check if this is the correct repo? Thanks!

**Comment by kumar303** [comment]
I see that you commented on https://github.com/mozilla/web-ext/issues/118 but I do not see anything related to source-map-support in your stack trace. Were you really seeing an error about source-map-support?

**Comment by ManuJindal** [comment]
@shubheksha  no.this is not define there

**Comment by shubheksha** [comment]
@ManuJindal, are you still facing this issue?
